"""SV-motor: núcleo local mínimo y auditable del frente motor del SV."""

from sv_motor.algebra.core import (
    U,
    K3_APTO,
    K3_INDETERMINADO,
    K3_NO_APTO,
    SVTernaryError,
    threshold,
    validate_cell_size,
    normalize_vector,
    classify_cell,
    summarize_cell,
    gate,
    gate_chain,
    gate_value,
    gate_vector,
    gamma_h_labels,
    gamma_bar_h,
    kappa3,
    resolve_policy,
)
from sv_motor.algebra.nlp import Observables, i_nlp, observables_from_dict, run_agent
from sv_motor.extractors.ext_nlp import validate_observables_dict, validate_observables_with_ud

from sv_motor.algebra.dev import (
    DevObservables,
    DEV_SUPPORT_BASE,
    i_dev,
    dev_observables_from_dict,
    resolve_dev_policy,
    run_dev_agent,
)

from sv_motor.security.custodia_estructural import (
    CustodiaMotorObservables,
    CUSTODIA_SUPPORT_BASE,
    i_custodia_motor,
    custodia_observables_from_dict,
    resolve_custodia_policy,
    run_custodia_motor,
    sensitive_step_is_allowed,
)

from sv_motor.protocols.ft_sv_ia import (
    ACTIVATION_PHRASE,
    INACTIVE_MESSAGE,
    build_session_declaration,
    build_state_block,
    render_protocol_output,
    run_direct_ft_session,
)


from sv_motor.verification import (
    SVProgramResult,
    run_nlp as verification_run_nlp,
    run_dev as verification_run_dev,
    run_custodia as verification_run_custodia,
    run_custom as verification_run_custom,
    ComparisonResult,
    compare as verification_compare,
    verify_reproducible,
)
__all__ = [
    "U",
    "K3_APTO",
    "K3_INDETERMINADO",
    "K3_NO_APTO",
    "SVTernaryError",
    "threshold",
    "validate_cell_size",
    "normalize_vector",
    "classify_cell",
    "summarize_cell",
    "gate",
    "gate_chain",
    "gate_value",
    "gate_vector",
    "gamma_h_labels",
    "gamma_bar_h",
    "kappa3",
    "resolve_policy",
    "Observables",
    "i_nlp",
    "observables_from_dict",
    "run_agent",
    "validate_observables_dict",
    "validate_observables_with_ud",
    "DevObservables",
    "DEV_SUPPORT_BASE",
    "i_dev",
    "dev_observables_from_dict",
    "resolve_dev_policy",
    "run_dev_agent",
    "CustodiaMotorObservables",
    "CUSTODIA_SUPPORT_BASE",
    "i_custodia_motor",
    "custodia_observables_from_dict",
    "resolve_custodia_policy",
    "run_custodia_motor",
    "sensitive_step_is_allowed",
    "ACTIVATION_PHRASE",
    "INACTIVE_MESSAGE",
    "build_session_declaration",
    "build_state_block",
    "render_protocol_output",
    "run_direct_ft_session",
    "SVProgramResult",
    "verification_run_nlp",
    "verification_run_dev",
    "verification_run_custodia",
    "verification_run_custom",
    "ComparisonResult",
    "verification_compare",
    "verify_reproducible",
]
