[workspace]
[package]
name = "eio-conversacion"
version = "0.1.1"
edition = "2021"
rust-version = "1.98"
publish = false

[[bin]]
name = "eio-conversacion"
path = "src/main.rs"

[dependencies]
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.145"
sha2 = { version = "=0.10.9", default-features = false, features = ["std"] }
axum = { version = "=0.8.9", default-features = false, features = ["http1", "json", "tokio"] }
tokio = { version = "=1.53.1", default-features = false, features = ["rt-multi-thread", "macros", "net", "sync", "time", "signal"] }
nix = { version = "=0.31.3", default-features = false, features = ["signal", "process", "fs", "feature"] }
candle-core = { git = "https://github.com/huggingface/candle", rev = "ddf1b879dc3a1760cbcb3f3c4a7c6467850cec4a", default-features = false }
candle-transformers = { git = "https://github.com/huggingface/candle", rev = "ddf1b879dc3a1760cbcb3f3c4a7c6467850cec4a", default-features = false }
tokenizers = { version = "=0.23.1", default-features = false, features = ["fancy-regex"] }

[profile.release]
debug = 0
incremental = false
