[book]
title = "Lenguaje SV · edición documental de prueba"
language = "es"
src = "src"

[build]
build-dir = "salida"
create-missing = false
use-default-preprocessors = false

[output.html]
mathjax-support = false
no-section-label = true
smart-punctuation = false
git-repository-url = "https://github.com/juantoniolloretegea/SV-lenguaje-de-computacion/tree/main/docs/manual_svp"

[output.html.playground]
runnable = false
editable = false
copy-js = false

[output.html.search]
enable = true
