const fs=require('fs'),path=require('path'),assert=require('assert');
const repo=process.argv[2],motor=process.argv[3];assert(/^[0-9a-f]{40}$/.test(motor));
const p={sc:'docs/calidad/Inventario-sv/sucesos/SUCESOS_SV.csv',sm:'docs/calidad/Inventario-sv/sucesos/SUCESOS_SV.md',sh:'docs/calidad/Inventario-sv/sucesos/HISTORIAL_SUCESOS_SV.csv',pc:'docs/calidad/REGISTRO_PARTES_DE_TRABAJO_POR_AGENTE.csv',pm:'docs/calidad/REGISTRO_PARTES_DE_TRABAJO_POR_AGENTE.md',rc:'docs/calidad/REGISTRO_EVOLUCION_TECNICA_PROYECTO.csv',rm:'docs/calidad/REGISTRO_EVOLUCION_TECNICA_PROYECTO.md',a4:'docs/calidad/tuberias-ia/continuacion-15-09-2026/ACTA_004_FINALIDAD_ALCANCE_Y_CONTINUIDAD_EIO_2026_09_22.md',a3:'docs/calidad/tuberias-ia/continuacion-15-09-2026/ACTA_003_CONCILIACION_EIO_SUCESOS_Y_CALIDAD_2026_09_20.md',inicio:'docs/calidad/tuberias-ia/continuacion-15-09-2026/inicio.md',leame:'docs/calidad/tuberias-ia/frame-significado-humano-trazabilidad-y-fidelidad/LEAME_PRIMERO.md'};
const old=Object.fromEntries(Object.entries(p).map(([k,f])=>[k,fs.readFileSync(path.join(repo,f),'utf8')])),out={},checks=[];
function parse(s){let o=[],r=[],v='',q=false;for(let i=0;i<s.length;i++){const c=s[i];if(c==='"'){if(q&&s[i+1]==='"'){v+='"';i++}else q=!q}else if(c===','&&!q){r.push(v);v=''}else if(c==='\n'&&!q){r.push(v.replace(/\r$/,''));o.push(r);r=[];v=''}else v+=c}assert(!q);if(r.length||v){r.push(v);o.push(r)}return o}
const csv=a=>a.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',');const check=(n,c)=>{assert(c,n);checks.push({control:n,correcto:true})};
const now=new Date().toISOString(),hora=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Madrid',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).format(new Date(now));
const link='https://github.com/juantoniolloretegea/SV-motor/blob/'+motor+'/laboratorio/ensayo-ia-y-observabilidad/modelos-de-ia/openai/gpt-oss-20b/resultados/onecloud-2026-09-24/optimizacion/RESULTADO.md';
const rows=parse(old.sc),h=rows[0],before=rows.find(r=>r[0]==='S39'),s=Object.fromEntries(h.map((k,i)=>[k,before[i]]));
s.fecha_actualizacion_utc=now;s.unidad_responsable='Unidad de ejecución experimental S39';
s.cortes_de_entrada+=' Recepción revisión 18: Lenguaje 32bf520f6e6c63dae84ef299957b6fd0b8c20402; protocolo Motor 7a3a353f55f8fddf5898eae9c82feb2caeac4677; originales daa3d3ec10d7f77e52572704832e76fdd87d3e10; informe Motor '+motor+'.';
s.resultado='Optimización CPU MXFP4 y sesión residente aceptadas de forma acotada: cinco casos correctos, con tres repeticiones C01; mediana 94,002 a 18,168 s en el mismo ejecutable. Banco finalizado a las 12:27:20,066 UTC dentro de la primera ventana. No se activa llama.cpp. TT-0012 conserva su cierre material anterior; S39 permanece abierto.';
s.verificacion='VERIFICACION_ACOTADA: un único binario y mismos pesos; tres pruebas numéricas específicas, nueve guardas y Cargo check aprobados. Diez peticiones en dos sesiones; 26 controles instrumentales Rust aprobados, HTTP íntegro, juicio semántico explícito, consumos, contadores finales y cierres conservados. No suite integral del motor ni certificación general.';
s.evidencias+=' ; '+link;s.referencia_calidad+=' S39 revisión 18; Acta004 §18; RETP-2026-271; PTA-2026-013; PTA-SVM-004.';
s.siguiente_accion='Conservar esta revisión como candidata. Una futura ampliación a tareas representativas y contexto progresivo requiere protocolo, oráculos y plazo nuevos. No hay inferencia activa de esta campaña. La alternativa llama.cpp queda disponible, sin resultado atribuido. S42/TT-0010 mantienen su alcance PC.';
s.observaciones='Factor de aceleración observado 5,174 y reducción 80,673 % para C01; no extrapolable. Tres repeticiones por modo, orden fijo, contexto pequeño, sin control exhaustivo de carga externa y cachés. No se separa el efecto de retirar copias del de paralelizar. Sin recursos adquiridos ni ramas adicionales. Historial, otros sucesos, rectores y mapa HTML conservados.';
out.sc=old.sc.split('\n').map(l=>l&&parse(l)[0]?.[0]==='S39'?csv(h.map(k=>s[k])):l).join('\n');
out.sh=old.sh.trimEnd()+'\n'+csv(['18',...h.map(k=>s[k])])+'\n';
check('Bloque S39 único',(old.sm.match(/^## S39 /gm)||[]).length===1);
out.sm=old.sm.replace(/## S39[\s\S]*?(?=## S40)/,'## S39 · '+s.actividad+'\n\n'+Object.entries(s).filter(([k])=>!['id','actividad'].includes(k)).map(([k,v])=>'**'+k+':** '+(v||'—')).join('\n\n')+'\n\n');
const part=['PTA-2026-013','24/09/2026',hora,'Unidad de ejecución experimental','VERIFICACION_ACOTADA','Recepción de optimización CPU MXFP4 y sesión residente','Lenguaje 32bf520; Motor '+motor,'Continuación autorizada y acotada de S39, tras PTA012','Recepción de protocolo, fuentes, dos bancos, auditoría, cierre y conciliación documental','Rectores vigentes; Acta004; originales y resultado Motor','Aceptación limitada a cinco casos y mejora temporal; S39 abierto','Sin llama.cpp, compras ni ramas adicionales; TT0012 conserva cierre material'];
out.pc=old.pc.trimEnd()+'\n'+csv(part)+'\n';
out.pm=old.pm.trimEnd()+`\n\n## PTA-2026-013 · Optimización CPU y ejecución residente\n\n**Registro:** ${now}; ${hora}, Europe/Madrid. **Unidad:** Unidad de ejecución experimental. **Base:** VERIFICACION_ACOTADA sobre Lenguaje 32bf520 y [Motor](${link}).\n\nSe reciben protocolo previo, fuentes, tres pruebas numéricas, nueve guardas, Cargo check, diez peticiones en dos sesiones y 26 controles instrumentales. Cinco casos correctos y mediana 94,002 a 18,168 s; cierre del banco a las 12:27:20,066 UTC. Se cumple el criterio de primera fase; llama.cpp no se activa.\n\nSe concilian S39 revisión 18, historial, RETP-2026-271, Acta004 §18 y accesos. TT-0012 conserva el cierre material anterior. Sin compras, ramas adicionales ni inferencia activa. Banco pequeño, orden fijo y ausencia de aislamiento entre las dos optimizaciones; no se certifica calidad general ni integración.\n`;
const retp=['RETP-2026-271','2026-09-24',hora,'Aceptación experimental acotada de rendimiento','S39 / EIO','Optimización MXFP4 y sesión residente: cinco casos correctos; mediana 94,002 a 18,168 s','Reducir latencia y evitar recargas dentro del banco, manteniendo criterios previos y trazabilidad','Rectores de pilares, perfiles y transición; Acta004; protocolo publicado antes del banco','S39 CSV/MD/historial; partes; RETP; Actas; accesos; control documental',link,'Revisión candidata aceptada para este banco; llama.cpp no activado','Orden fijo y banco pequeño; no se separan copias y paralelización; no generalización','Conservar resultados y preparar futuras tareas representativas con protocolo nuevo','en ejecución'];
out.rc=old.rc.trimEnd()+'\n'+csv(retp)+'\n';
out.rm=old.rm.trimEnd()+`\n\n## RETP-2026-271 · Optimización CPU y ejecución residente\n\n**Registro:** ${now}; ${hora}, Europe/Madrid. Unidad de ejecución experimental; VERIFICACION_ACOTADA.\n\n[Motor ${motor}](${link}) documenta comparación dentro del mismo binario, cinco casos correctos, mediana de 94,002 a 18,168 s, contención y cierre. La primera ventana termina con criterio cumplido; no se activa la alternativa C/C++. S39 revisión 18; Acta004 §18; PTA-2026-013 y PTA-SVM-004.\n\nSe conserva el cierre material de TT-0012. La aceleración observada no acredita calidad general, rendimiento de conversaciones largas ni causalidad separada de ambas optimizaciones. Los originales y resultados históricos adversos permanecen. Próximo trabajo: protocolo nuevo para tareas representativas, sin ejecución atribuida en esta recepción.\n`;
out.a4=old.a4.trimEnd()+`\n\n## 18. Optimización CPU MXFP4 y ejecución residente · 24/09/2026\n\n**Registro:** ${now}. Unidad de ejecución experimental. **Base:** VERIFICACION_ACOTADA sobre Lenguaje 32bf520f6e6c63dae84ef299957b6fd0b8c20402 y [Motor ${motor}](${link}).\n\n### 18.1. Diseño y hechos recibidos\n\nAutorización de dos ventanas consecutivas de una hora desde 11:58 UTC: optimización Rust y residencia hasta 12:58; llama.cpp condicional hasta 13:58. Sin adquisición adicional. Protocolo publicado antes de inferencia en 7a3a353; corrección de ubicación documental en 388933b sin alterar criterios.\n\nUn mismo motor permite seleccionar referencia secuencial y variante paralela sin copias completas de bloques y escalas contiguos. Mismos pesos, tokenizador, parámetros y trabajadores. Tres solicitudes C01 de referencia y siete candidatas en dos sesiones residentes, una inferencia a la vez. Tres pruebas numéricas específicas, nueve guardas y Cargo check aprobados. Rust 1.98.0; sin Python.\n\n### 18.2. Dictamen acotado\n\nCinco casos correctos, incluidas las tres repeticiones C01. Mediana HTTP 94,002 a 18,168 s: factor 5,174, reducción 80,673 %. Se satisface el umbral previo de reducción mínima del 50 %. Banco candidato finalizado a las 12:27:20,066 UTC, dentro de la primera fase. **Aceptación experimental acotada de la revisión. No se activa llama.cpp.**\n\nLos 26 controles instrumentales de originales aprueban; el juicio semántico se registra aparte. Todas las respuestas terminan con stop. Los dos hijos y servicios están detenidos, sin errores; contadores finales de la cuota exterior sin eventos max, oom ni oom_kill. La máquina continúa disponible, sin modelo residente de esta campaña.\n\n### 18.3. Objeciones y límites\n\nTres repeticiones de una tarea temporal y cinco casos sintéticos, contexto 1024, orden fijo, sin aleatorización ni control exhaustivo de cachés o carga externa. Se comparan juntas retirada de copias y paralelización; no se atribuye una fracción causal separada a cada una. La residencia se observa, pero su ganancia frente a recargar por petición no se mide de forma independiente. RSS y memory.peak pertenecen a ámbitos distintos. No hay suite integral ni certificación general, conversacional o productiva.\n\n### 18.4. Trazabilidad y continuidad\n\nS39 revisión 18, RETP-2026-271, PTA-2026-013 y PTA-SVM-004; [control documental](CONTROL_OPTIMIZACION_2026_09_24.md). TT-0012 conserva su cierre material; S39 permanece abierto para otra fase con protocolo y plazo nuevos. Qwen/B, S42/TT-0010, otros sucesos, rectores, núcleo y mapa HTML conservan sus alcances. No se crean ramas adicionales ni se compran recursos. Los apartados anteriores mantienen sus cortes históricos.\n`;
out.a3=old.a3.trimEnd()+`\n\n## Remisión vigente · Optimización y residencia · ${now}\n\n[Informe experimental](${link}) y Acta004 §18: cinco casos correctos, mediana 94,002 a 18,168 s y cierre completo dentro de primera ventana. S39 revisión 18; RETP-2026-271; PTA-2026-013; PTA-SVM-004. TT-0012 mantiene cierre material. Llama.cpp no activado. Los cortes anteriores permanecen históricos.\n`;
for(const k of ['inicio','leame']){const i=old[k].indexOf('\n');out[k]=old[k].slice(0,i)+`\n\n**Recepción vigente · ${now}:** [Optimización CPU y ejecución residente](${link}). Cinco casos correctos; mediana 94,002 a 18,168 s; criterio acotado cumplido en la primera ventana y servicios detenidos. S39 revisión 18; Acta004 §18; RETP-2026-271; PTA-2026-013; PTA-SVM-004. TT-0012 mantiene su cierre material.\n`+old[k].slice(i);}
const after=parse(out.sc);check('Mismo número de sucesos',after.length===rows.length);for(let i=1;i<rows.length;i++)if(rows[i][0]!=='S39')check('Suceso conservado '+rows[i][0],JSON.stringify(rows[i])===JSON.stringify(after[i]));
check('Alta S39 conservada',s.fecha_alta_utc===before[h.indexOf('fecha_alta_utc')]);check('Inicio S39 conservado',s.fecha_inicio_utc===before[h.indexOf('fecha_inicio_utc')]);check('S39 abierto',s.estado==='en ejecución'&&s.fecha_fin_utc==='');
check('Historial conservado',out.sh.startsWith(old.sh.trimEnd()));check('Revisión 18 única',parse(out.sh).filter(r=>r[0]==='18'&&r[1]==='S39').length===1);check('Historial concordante',JSON.stringify(parse(out.sh).at(-1).slice(1))===JSON.stringify(h.map(k=>s[k])));
for(const k of ['sc','sh','pc','rc']){const rs=parse(out[k]);check('Ancho CSV '+k,rs.every(r=>r.length===rs[0].length));}
for(const [k,id]of [['pc','PTA-2026-013'],['rc','RETP-2026-271']]){check('Identificador único '+id,parse(out[k]).filter(r=>r[0]===id).length===1);check('Histórico conservado '+k,out[k].startsWith(old[k].trimEnd()));}
check('Otros bloques Markdown conservados',old.sm.replace(/## S39[\s\S]*?(?=## S40)/,'')===out.sm.replace(/## S39[\s\S]*?(?=## S40)/,''));
check('Acta histórica conservada',out.a4.startsWith(old.a4.trimEnd()));
check('Sin archivos HTML',Object.keys(out).every(k=>!p[k].endsWith('.html')));
const control=`# Control documental de optimización y residencia\n\nRegistro ${now}. Unidad de ejecución experimental. Verificación limitada a los registros modificados; no auditoría global.\n\n${checks.length} comprobaciones estructurales aprobadas: otros sucesos conservados, fechas originales de S39, estado abierto, historial íntegro, revisión 18 concordante, anchos CSV, nuevos asientos únicos y cortes históricos preservados. TT-0012 y el índice de tiques no se modifican. Las duplicidades RETP históricas previamente conocidas se conservan; no se declara unicidad global.\n\n[Informe y originales](${link}). Estos controles son documentales, no ensayos adicionales del modelo.\n\n${checks.map(c=>'- Aprobado: '+c.control+'.').join('\n')}\n`;
for(const [k,v]of Object.entries(out))fs.writeFileSync(path.join(repo,p[k]),v);
fs.writeFileSync(path.join(repo,'docs/calidad/tuberias-ia/continuacion-15-09-2026/CONTROL_OPTIMIZACION_2026_09_24.md'),control);
console.log(JSON.stringify({fecha_utc:now,archivos:Object.keys(out).length+1,controles:checks.length,revision_s39:18,referencia_motor:motor}));
