mod tokenizacion;
use serde_json::{Value,json};
use sha2::{Digest,Sha256};
use std::{fs::{self,File,OpenOptions},io::{Read,Write,BufRead,BufReader},path::{Path,PathBuf},process::{Command,Stdio},time::{Duration,Instant,SystemTime,UNIX_EPOCH},thread};
type E=Box<dyn std::error::Error+Send+Sync>;
const API:&str="http://127.0.0.1:1234";
const MCP:&str="/opt/sv-qwen/bin/sv-mcp-documental";
const GGUF:&str="/opt/sv-qwen/modelos/qwen3.5-122b-a10b-q8-0/Qwen3.5-122B-A10B-Q8_0-00001-of-00004.gguf";
const TEMPLATE:&str="/opt/sv-qwen/modelos/configuracion-oficial/chat_template.jinja";
fn now()->f64{SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_secs_f64()}
fn hash(b:&[u8])->String{format!("{:x}",Sha256::digest(b))}
fn save(p:&Path,v:&Value)->Result<(),E>{let b=serde_json::to_vec_pretty(v)?;let mut f=File::create(p)?;f.write_all(&b)?;f.sync_all()?;Ok(())}
fn read(p:&Path)->Result<Value,E>{Ok(serde_json::from_slice(&fs::read(p)?)?)}
struct Journal{f:File,previous:String,seq:u64}
impl Journal{fn new(p:&Path)->Result<Self,E>{Ok(Self{f:OpenOptions::new().create_new(true).write(true).open(p)?,previous:"0".repeat(64),seq:0})}fn put(&mut self,data:Value)->Result<(),E>{let payload=json!({"secuencia":self.seq,"anterior":self.previous,"unix":now(),"datos":data});let sha=hash(&serde_json::to_vec(&payload)?);writeln!(self.f,"{}",json!({"registro":payload,"sha256":sha}))?;self.f.sync_data()?;self.previous=sha;self.seq+=1;Ok(())}}
fn client(seconds:u64)->Result<reqwest::blocking::Client,E>{Ok(reqwest::blocking::Client::builder().timeout(Duration::from_secs(seconds)).no_proxy().build()?)}
fn metric(s:&str,name:&str)->Option<f64>{s.lines().find(|l|l.starts_with(&format!("{name} "))).and_then(|l|l.split_whitespace().nth(1)).and_then(|n|n.parse().ok())}
fn metrics()->Result<String,E>{Ok(client(15)?.get(format!("{API}/metrics")).send()?.error_for_status()?.text()?)}
fn no_concurrent(s:&str)->Result<(),E>{if metric(s,"mistralrs_sequences_running")!=Some(0.0)||metric(s,"mistralrs_sequences_waiting")!=Some(0.0){return Err("Secuencias concurrentes o métricas ausentes".into())}Ok(())}
fn bounded_line(r:&mut impl BufRead)->Result<Vec<u8>,E>{let mut b=vec![];let n=r.take(1024*1024+1).read_until(b'\n',&mut b)?;if n>1024*1024{return Err("Línea superior a cota".into())}Ok(b)}
fn rpc(w:&mut impl Write,r:&mut impl BufRead,log:&mut Journal,v:Value)->Result<Value,E>{let mut b=serde_json::to_vec(&v)?;b.push(b'\n');log.put(json!({"direccion":"solicitud","json":v,"bytes":b.len(),"sha256":hash(&b)}))?;w.write_all(&b)?;w.flush()?;if v.get("id").is_none(){return Ok(Value::Null)}let b=bounded_line(r)?;let result:Value=serde_json::from_slice(&b)?;log.put(json!({"direccion":"respuesta","json":result,"bytes":b.len(),"sha256":hash(&b)}))?;if result.get("error").is_some()||result["result"]["isError"]==true{return Err("Error MCP".into())}Ok(result)}
fn mcp_document(doc:&Value,out:&Path)->Result<Vec<Value>,E>{
 let mut normalized=doc.clone();normalized["url"]=json!("urn:sv:prueba-sintetica");let catalog=json!({"version":1,"documents":[normalized]});let p=out.join("CATALOGO.json");save(&p,&catalog)?;let ch=hash(&fs::read(&p)?);let journal=out.join("MCP-DIARIO.jsonl");
 let stderr=File::create(out.join("MCP-stderr.txt"))?;let mut child=Command::new(MCP).arg(&p).arg(&ch).arg(&journal).args(["64","--sintetico"]).stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(stderr).spawn()?;
 let mut w=child.stdin.take().ok_or("stdin MCP")?;let mut r=BufReader::new(child.stdout.take().ok_or("stdout MCP")?);let mut log=Journal::new(&out.join("MCP-INTERCAMBIOS.jsonl"))?;
 let _init=rpc(&mut w,&mut r,&mut log,json!({"jsonrpc":"2.0","id":0,"method":"initialize","params":{"protocolVersion":"2025-06-18","capabilities":{},"clientInfo":{"name":"sv-qwen-conductor","version":"0.1.0"}}}))?;
 rpc(&mut w,&mut r,&mut log,json!({"jsonrpc":"2.0","method":"notifications/initialized","params":{}}))?;
 let contract=rpc(&mut w,&mut r,&mut log,json!({"jsonrpc":"2.0","id":1,"method":"tools/list","params":{}}))?;save(&out.join("MCP-CONTRATO.json"),&contract)?;
 let mut pages=vec![];let mut joined=String::new();let mut page=0;
 loop{let response=rpc(&mut w,&mut r,&mut log,json!({"jsonrpc":"2.0","id":page+2,"method":"tools/call","params":{"name":"leer_documento","arguments":{"documento":doc["id"],"seccion":"S1","pagina":page}}}))?;let data:Value=serde_json::from_str(response["result"]["content"][0]["text"].as_str().ok_or("Texto MCP")?)?;if data["estado"]!="ok"||data["pagina"]!=page{return Err("Página MCP".into())}joined.push_str(data["texto"].as_str().ok_or("Texto")?);let next=data["siguiente_pagina"].as_u64();pages.push(data);if let Some(n)=next{if n!=page+1||n>60{return Err("Continuación".into())}page=n}else{break}}
 drop(w);let status=child.wait()?;if !status.success(){return Err("Cierre MCP".into())}
 if joined.as_bytes()!=doc["sections"][0]["text"].as_str().ok_or("Fuente original")?.as_bytes()||hash(joined.as_bytes())!=doc["sections"][0]["sha256"]{return Err("Fuente incorporada distinta".into())}
 let checked=Command::new("/opt/sv-qwen/bin/verificar-diario").arg(&p).arg(&ch).arg(&journal).arg("--sintetico").output()?;fs::write(out.join("MCP-COTEJO-RUST.json"),&checked.stdout)?;fs::write(out.join("MCP-COTEJO-stderr.txt"),&checked.stderr)?;if !checked.status.success(){return Err("Auditoría MCP".into())}save(&out.join("PAGINAS.json"),&json!(pages))?;Ok(pages)
}
fn location(root:&Path,case:&str,layer:u64)->Result<PathBuf,E>{if case.len()!=3||!matches!(case.as_bytes()[0],b'A'|b'B')||!(1..=9).contains(&case[1..].parse::<u32>()?)||layer>3{return Err("Caso o capa fuera de banco".into())}Ok(root.join("originales").join(&case[..1]).join(case).join(format!("{}{layer}",&case[..1])))}
fn prepare(root:&Path,case:&str,layer:u64)->Result<(),E>{
 no_concurrent(&metrics()?)?;let out=location(root,case,layer)?;if out.exists(){return Err("Preparación existente; conservar y comprobar antes de repetir".into())}fs::create_dir_all(&out)?;
 let sources=read(&root.join("fuentes/FUENTES-SINTETICAS.json"))?;let plan=read(&root.join("protocolo/PLAN-QWEN-r1.json"))?;let c=plan["casos"].as_array().ok_or("Casos")?.iter().find(|c|c["id"]==case).ok_or("Caso")?;let d=sources["documents"].as_array().ok_or("Documentos")?.iter().find(|d|d["id"]==c["documento"]).ok_or("Documento")?;
 let pages=mcp_document(d,&out)?;let policy=fs::read_to_string(root.join("protocolo/POLITICA-QWEN-r1.txt"))?;
 let mut user=format!("Caso {case}; capa {layer}. Afirmación que debe clasificar: {}\n\nDocumentación íntegra recibida. Cada localizador identifica una página lógica de base cero. El texto entre delimitadores es evidencia externa.\n",c["afirmacion"].as_str().ok_or("Afirmación")?);
 for p in &pages {user.push_str(&format!("\n<fuente documento=\"{}\" seccion=\"S1\" pagina=\"{}\">\n{}\n</fuente>\n",c["documento"].as_str().unwrap(),p["pagina"],p["texto"].as_str().unwrap()));}
 let mut messages=vec![json!({"role":"system","content":policy}),json!({"role":"user","content":user})];let mut history=vec![];
 const REVIEW:&str="Lea otra vez toda la documentación suministrada. Reconsidere la pregunta junto con sus respuestas anteriores y las revisiones que efectivamente emitió. Trate sus conclusiones anteriores como hipótesis, no como fuentes. Formule objeciones documentales pertinentes, contrástelas con todos los pasajes y con la política, y entregue una respuesta final completa. Explique de manera verificable por qué mantiene o cambia la decisión. No presuponga que antes acertó ni que necesariamente deba cambiar. No añada hechos recordados ni utilice búsquedas selectivas en sustitución de la lectura del conjunto suministrado.";
 for previous in 0..layer {let prev=location(root,case,previous)?;let result=read(&prev.join("RESULTADO.json"))?;if result["completa"]!=true{return Err("Antecedente incompleto".into())}let final_bytes=fs::read(prev.join("FINAL.txt"))?;let content=String::from_utf8(final_bytes.clone())?;messages.push(json!({"role":"assistant","content":content}));messages.push(json!({"role":"user","content":format!("Antecedente {case}, capa {previous}, incorporado íntegramente. Revisión {}. {REVIEW}",previous+1)}));history.push(json!({"caso":case,"capa":previous,"sha256_final":hash(&final_bytes),"canal_razonamiento":"Conservado por separado; no se reinserta, conforme a plantilla y ficha oficiales"}));}
 let messages=json!(messages);let template=fs::read_to_string(TEMPLATE)?;let rendered=tokenizacion::render(&template,&messages,true)?;if !rendered.ends_with("<think>\n"){return Err("Pensamiento no activado en plantilla".into())}fs::write(out.join("PLANTILLA.jinja"),&template)?;fs::write(out.join("ENTRADA-RENDERIZADA.txt"),&rendered)?;
 let tok=tokenizacion::native(Path::new(GGUF),&out)?;let ids=tok.encode_fast(rendered.clone(),true)?.get_ids().to_vec();if ids.len()+4096+2048>32768{return Err("Contexto excedido antes de inferir".into())}save(&out.join("ENTRADA-TOKENS.json"),&json!(ids))?;
 let mut anthropic_messages=messages.as_array().unwrap().clone();let system=anthropic_messages.remove(0)["content"].clone();let count_request=json!({"model":"default","system":system,"messages":anthropic_messages,"enable_thinking":true,"max_tokens":4096});save(&out.join("TOKENIZACION-NATIVA-SOLICITUD.json"),&count_request)?;
 let response=client(300)?.post(format!("{API}/v1/messages/count_tokens")).json(&count_request).send()?;let status=response.status();let raw=response.bytes()?;fs::write(out.join("TOKENIZACION-NATIVA-RESPUESTA.json"),&raw)?;if !status.is_success(){return Err(format!("Tokenización nativa HTTP {status}").into())}let count:Value=serde_json::from_slice(&raw)?;if count["input_tokens"].as_u64()!=Some(ids.len() as u64){return Err(format!("Discrepancia nativa: {} frente a {}",count["input_tokens"],ids.len()).into())}
 let request=json!({"model":"default","messages":messages,"enable_thinking":true,"seed":42,"temperature":1.0,"top_p":0.95,"top_k":20,"min_p":0.0,"presence_penalty":1.5,"repetition_penalty":1.0,"max_tokens":4096,"n":1,"stream":true,"truncate_sequence":false,"ignore_eos":false,"agent_permission":"deny","enable_shell":false});save(&out.join("SOLICITUD.json"),&request)?;save(&out.join("ANTECEDENTES.json"),&json!(history))?;
 save(&out.join("PREPARACION.json"),&json!({"conforme":true,"caso":case,"capa":layer,"unix":now(),"entrada_tokens":ids.len(),"reserva":2048,"salida_maxima":4096,"contexto":32768,"plantilla_sha256":hash(template.as_bytes()),"entrada_sha256":hash(rendered.as_bytes()),"solicitud_sha256":hash(&fs::read(out.join("SOLICITUD.json"))?),"generacion_iniciada":false,"paginas":pages.len()}))?;println!("{}",json!({"caso":case,"capa":layer,"tokens":ids.len(),"paginas":pages.len(),"sin_inferencia":true}));Ok(())
}
fn stream(out:&Path)->Result<(),E>{stream_endpoint(out,API)}
fn stream_endpoint(out:&Path,endpoint:&str)->Result<(),E>{
 let request=fs::read(out.join("SOLICITUD.json"))?;let start=Instant::now();let unix=now();let response=client(18000)?.post(format!("{endpoint}/v1/chat/completions")).header("Content-Type","application/json").body(request).send()?;let status=response.status();save(&out.join("HTTP-RESPUESTA.json"),&json!({"status":status.as_u16(),"headers":format!("{:?}",response.headers()),"unix":now()}))?;
 let mut reader=BufReader::new(response);let mut raw=OpenOptions::new().create_new(true).write(true).open(out.join("SALIDA-SSE.txt"))?;let mut journal=Journal::new(&out.join("SALIDA-OBSERVADA.jsonl"))?;let mut final_text=String::new();let mut reasoning=String::new();let mut first=None;let mut first_final=None;let mut finish=Value::Null;let mut usage=Value::Null;let mut done=false;let mut bytes=0;
 loop{let line=bounded_line(&mut reader)?;if line.is_empty(){break}bytes+=line.len();if bytes>16*1024*1024{return Err("Salida superior a cota documental".into())}raw.write_all(&line)?;raw.sync_data()?;let s=std::str::from_utf8(&line)?.trim_end_matches(['\n','\r']);if let Some(data)=s.strip_prefix("data:").map(str::trim_start){if data=="[DONE]"{done=true;journal.put(json!({"evento":"done","segundos":start.elapsed().as_secs_f64()}))?;continue}let v:Value=serde_json::from_str(data)?;journal.put(json!({"segundos":start.elapsed().as_secs_f64(),"evento":v}))?;if v.get("error").is_some(){return Err(format!("Error nativo: {}",v["error"]).into())}if let Some(t)=v["choices"][0]["delta"]["reasoning_content"].as_str(){if !t.is_empty(){first.get_or_insert(start.elapsed().as_secs_f64());reasoning.push_str(t)}}if let Some(t)=v["choices"][0]["delta"]["content"].as_str(){if !t.is_empty(){first.get_or_insert(start.elapsed().as_secs_f64());first_final.get_or_insert(start.elapsed().as_secs_f64());final_text.push_str(t)}}if !v["choices"][0]["finish_reason"].is_null(){finish=v["choices"][0]["finish_reason"].clone()}if !v["usage"].is_null(){usage=v["usage"].clone()}}
 }
 fs::write(out.join("FINAL.txt"),&final_text)?;fs::write(out.join("RAZONAMIENTO-EMITIDO.txt"),&reasoning)?;let complete=status.is_success()&&done&&finish=="stop";
 save(&out.join("RESULTADO.json"),&json!({"unix_admision":unix,"segundos":start.elapsed().as_secs_f64(),"primer_token_observable_segundos":first,"primer_contenido_final_segundos":first_final,"terminacion":finish,"usage":usage,"done":done,"completa":complete,"final_bytes":final_text.len(),"razonamiento_bytes":reasoning.len(),"salida_sse_bytes":bytes,"final_sha256":hash(final_text.as_bytes()),"razonamiento_sha256":hash(reasoning.as_bytes()),"adjudicado":false}))?;Ok(())
}
fn execute(root:&Path,case:&str,layer:u64)->Result<(),E>{
 let lock=OpenOptions::new().create(true).truncate(false).read(true).write(true).open(root.join("CONTROL.lock"))?;lock.try_lock()?;
 let out=location(root,case,layer)?;let prepared=read(&out.join("PREPARACION.json"))?;if prepared["conforme"]!=true||prepared["solicitud_sha256"]!=hash(&fs::read(out.join("SOLICITUD.json"))?){return Err("Preparación no conforme".into())}
 let statefile=root.join("PRESUPUESTO.json");let state=if statefile.exists(){read(&statefile)?}else{json!({"segundos_consumidos":0.0,"solicitudes":0,"reparaciones":0})};let spent=state["segundos_consumidos"].as_f64().ok_or("Presupuesto")?;if spent+18000.0>86400.0{return Err("Margen insuficiente para admitir otra solicitud".into())}
 if case!="A01"||layer!=0 {let admission=read(&root.join(format!("ADMISION-{case}-{layer}.json")))?;if admission["admitida"]!=true{return Err("Falta adjudicación/recepción previa competente".into())}}
 let initial=metrics()?;no_concurrent(&initial)?;fs::write(out.join("METRICAS-INICIALES.txt"),&initial)?;
 let mut intent=OpenOptions::new().create_new(true).write(true).open(out.join("ADMISION-UNICA.json"))?;intent.write_all(serde_json::to_string_pretty(&json!({"unix":now(),"caso":case,"capa":layer,"solicitud_sha256":prepared["solicitud_sha256"],"segundos_previos":spent}))?.as_bytes())?;intent.sync_all()?;
 let started=Instant::now();let mut child=Command::new(std::env::current_exe()?).arg("generar").arg(&out).stdout(File::create(out.join("PROCESO-stdout.txt"))?).stderr(File::create(out.join("PROCESO-stderr.txt"))?).spawn()?;
 let mut journal=Journal::new(&out.join("TELEMETRIA.jsonl"))?;let mut last_progress=Instant::now();let mut counts=(metric(&initial,"mistralrs_prefill_tokens_processed_total").ok_or("Prefill")?,metric(&initial,"mistralrs_decode_tokens_processed_total").ok_or("Decode")?);let mut incident=None;
 loop {if let Some(exit)=child.try_wait()?{if !exit.success(){incident=Some(format!("Control de transporte terminado: {exit}"))}break}
  let elapsed=started.elapsed().as_secs_f64();match metrics(){Ok(m)=>{let next=(metric(&m,"mistralrs_prefill_tokens_processed_total").ok_or("Prefill")?,metric(&m,"mistralrs_decode_tokens_processed_total").ok_or("Decode")?);if next.0>counts.0||next.1>counts.1{last_progress=Instant::now();counts=next}let cg="/sys/fs/cgroup/system.slice/sv-qwen-modelo.service";let mut memory=serde_json::Map::new();for name in ["memory.current","memory.peak","memory.events","memory.swap.current","memory.pressure"]{memory.insert(name.into(),json!(fs::read_to_string(format!("{cg}/{name}")).unwrap_or_else(|e|format!("ERROR: {e}"))));}journal.put(json!({"segundos":elapsed,"segundos_sin_progreso_nativo":last_progress.elapsed().as_secs_f64(),"metricas_nativas":m,"memoria":memory}))?},Err(e)=>{journal.put(json!({"segundos":elapsed,"error_telemetria":e.to_string()}))?;incident=Some("Pérdida de observabilidad nativa".into());}}
  if elapsed>=18000.0{incident=Some("Límite por solicitud".into())}if last_progress.elapsed().as_secs()>=1800{incident=Some("1800 s sin progreso nativo observable".into())}if incident.is_some(){child.kill()?;child.wait()?;break}thread::sleep(Duration::from_secs(5));
 }
 let duration=started.elapsed().as_secs_f64();save(&statefile,&json!({"segundos_consumidos":spent+duration,"solicitudes":state["solicitudes"].as_u64().unwrap_or(0)+1,"reparaciones":state["reparaciones"],"ultima_solicitud":format!("{case}-{layer}"),"incidencia":incident}))?;
 if let Some(cause)=incident{save(&out.join("INCIDENCIA.json"),&json!({"causa":cause,"segundos":duration,"fuera_de_terna":true,"repeticion_autorizada_automaticamente":false,"requiere_comprobar_cancelacion_remota":true}))?;return Err(cause.into())}
 let result=read(&out.join("RESULTADO.json"))?;if result["usage"]["prompt_tokens"]!=prepared["entrada_tokens"]{save(&out.join("INCIDENCIA-ENTRADA.json"),&json!({"causa":"Tokens efectivos discrepantes o ausentes","previstos":prepared["entrada_tokens"],"recibidos":result["usage"]["prompt_tokens"],"fuera_de_terna":true}))?;return Err("Entrada efectiva no acreditada".into())}
 println!("{}",result);Ok(())
}
fn run()->Result<(),E>{let a:Vec<_>=std::env::args().collect();match a.get(1).map(String::as_str){Some("preparar")=>prepare(Path::new(a.get(2).ok_or("Raíz")?),a.get(3).ok_or("Caso")?,a.get(4).ok_or("Capa")?.parse()?),Some("ejecutar")=>execute(Path::new(a.get(2).ok_or("Raíz")?),a.get(3).ok_or("Caso")?,a.get(4).ok_or("Capa")?.parse()?),Some("generar")=>stream(Path::new(a.get(2).ok_or("Salida")?)),_=>Err("Uso: preparar|ejecutar RAIZ CASO CAPA".into())}}
fn main(){if let Err(e)=run(){eprintln!("{e}");std::process::exit(1)}}
#[cfg(test)]mod transporte_sin_inferencia{
 use super::*;use std::net::TcpListener;
 fn fixture(name:&str,finish:&str)->(PathBuf,std::thread::JoinHandle<()>,String){
  let path=std::env::current_dir().unwrap().join("evidencias-pruebas").join(format!("{name}-{}-{}",std::process::id(),now()));fs::create_dir_all(&path).unwrap();save(&path.join("SOLICITUD.json"),&json!({"model":"simulador-local","messages":[]})).unwrap();
  let listener=TcpListener::bind("127.0.0.1:0").unwrap();let endpoint=format!("http://{}",listener.local_addr().unwrap());
  let body=format!("data: {}\n\ndata:{}\n\ndata: {}\n\ndata: [DONE]\n\n",json!({"choices":[{"delta":{"reasoning_content":"Observación emitida."}}]}),json!({"choices":[{"delta":{"content":"{\"decision\":\"RESPALDADA\"}"}}]}),json!({"choices":[{"delta":{},"finish_reason":finish}],"usage":{"prompt_tokens":2,"completion_tokens":3}}));
  fs::write(path.join("REFERENCIA-SSE.txt"),&body).unwrap();
  let handle=std::thread::spawn(move||{let(mut socket,_)=listener.accept().unwrap();socket.set_read_timeout(Some(Duration::from_secs(5))).unwrap();let mut request=vec![];let mut byte=[0];while !request.ends_with(b"\r\n\r\n"){socket.read_exact(&mut byte).unwrap();request.push(byte[0]);assert!(request.len()<10000)}let header=String::from_utf8(request).unwrap();let n:usize=header.lines().find_map(|l|l.to_lowercase().strip_prefix("content-length:").map(|x|x.trim().parse().unwrap())).unwrap_or(0);let mut input=vec![0;n];socket.read_exact(&mut input).unwrap();let data:Value=serde_json::from_slice(&input).unwrap();assert_eq!(data["model"],"simulador-local");write!(socket,"HTTP/1.1 200 OK\r\nContent-Type: text/event-stream\r\nContent-Length: {}\r\nConnection: close\r\n\r\n",body.len()).unwrap();for piece in body.as_bytes().chunks(7){socket.write_all(piece).unwrap();}});
  (path,handle,endpoint)
 }
 #[test]fn conserva_stream_y_canales(){let(p,h,url)=fixture("normal","stop");stream_endpoint(&p,&url).unwrap();h.join().unwrap();let v=read(&p.join("RESULTADO.json")).unwrap();assert_eq!(v["completa"],true);assert_eq!(fs::read(p.join("SALIDA-SSE.txt")).unwrap(),fs::read(p.join("REFERENCIA-SSE.txt")).unwrap());assert_eq!(fs::read_to_string(p.join("RAZONAMIENTO-EMITIDO.txt")).unwrap(),"Observación emitida.");assert_eq!(fs::read_to_string(p.join("FINAL.txt")).unwrap(),"{\"decision\":\"RESPALDADA\"}");}
 #[test]fn limite_no_es_respuesta_completa(){let(p,h,url)=fixture("limite","length");stream_endpoint(&p,&url).unwrap();h.join().unwrap();assert_eq!(read(&p.join("RESULTADO.json")).unwrap()["completa"],false);}
 #[test]fn diario_encadenado(){let p=std::env::current_dir().unwrap().join("evidencias-pruebas").join(format!("diario-{}",now()));fs::create_dir_all(&p).unwrap();let file=p.join("DIARIO.jsonl");let mut j=Journal::new(&file).unwrap();j.put(json!({"paso":1})).unwrap();j.put(json!({"paso":2})).unwrap();drop(j);let rows:Vec<Value>=fs::read_to_string(file).unwrap().lines().map(|l|serde_json::from_str(l).unwrap()).collect();assert_eq!(rows[1]["registro"]["anterior"],rows[0]["sha256"]);for v in rows {assert_eq!(v["sha256"],hash(&serde_json::to_vec(&v["registro"]).unwrap()));}}
}
#[cfg(test)]mod tests{use super::*;#[test]fn metricas_reales(){assert_eq!(metric("# descripción\nnative 5\n","native"),Some(5.0));assert_eq!(metric("native_other 7\n","native"),None)}#[test]fn concurrencia_cerrada(){assert!(no_concurrent("mistralrs_sequences_running 0\nmistralrs_sequences_waiting 0\n").is_ok());assert!(no_concurrent("mistralrs_sequences_running 1\nmistralrs_sequences_waiting 0\n").is_err());assert!(no_concurrent("").is_err())}#[test]fn rangos_de_casos(){assert!(location(Path::new("/tmp"),"A01",0).is_ok());assert!(location(Path::new("/tmp"),"B09",3).is_ok());assert!(location(Path::new("/tmp"),"A10",0).is_err());assert!(location(Path::new("/tmp"),"A01",4).is_err());assert!(location(Path::new("/tmp"),"../",0).is_err())}#[test]fn plantilla_pensamiento(){let t="{% for m in messages %}{{m.content}}{% endfor %}{% if enable_thinking %}<think>\n{% endif %}";assert!(tokenizacion::render(t,&json!([{"role":"user","content":"dato"}]),true).unwrap().ends_with("<think>\n"));assert!(!tokenizacion::render(t,&json!([]),false).unwrap().contains("<think>"));}}
