use std::{collections::BTreeSet,fs,io::Write,path::Path,time::{SystemTime,UNIX_EPOCH}};
use serde_json::{Value,json};
use sv_arbitro_comprobaciones::{huella,auditoria::auditar};
type R<T>=Result<T,Box<dyn std::error::Error>>;
fn ck(b:bool,s:&str)->R<()>{if b{Ok(())}else{Err(s.into())}}
fn val(p:&Path)->R<Value>{Ok(serde_json::from_slice(&fs::read(p)?)?)}
fn txt(p:&Path)->R<String>{Ok(fs::read_to_string(p)?)}
fn save(p:&Path,v:&Value)->R<()>{let mut f=fs::OpenOptions::new().create_new(true).write(true).open(p)?;f.write_all(&serde_json::to_vec_pretty(v)?)?;f.sync_all()?;Ok(())}
fn norm(s:String)->Vec<String>{let mut a=s.lines().map(|s|s.split_whitespace().collect::<Vec<_>>().join(" ")).collect::<Vec<_>>();a.sort();a}
fn packages(s:&str)->R<BTreeSet<Vec<String>>>{
 let mut result=BTreeSet::new();
 for p in s.split("[[package]]").skip(1){
  let mut fields=Vec::new();
  for name in ["name","version","source","checksum"]{let prefix=format!("{name} = ");fields.push(p.lines().find_map(|l|l.strip_prefix(&prefix)).unwrap_or("").to_string());}
  ck(!fields[0].is_empty()&&!fields[1].is_empty(),"Identidad de dependencia incompleta")?;
  if !fields[2].is_empty(){result.insert(fields);}
 }ck(!result.is_empty(),"Dependencias ausentes")?;Ok(result)
}
fn record(root:&Path,rel:&str)->R<Value>{let b=fs::read(root.join(rel))?;Ok(json!({"ruta":rel,"bytes":b.len(),"sha256":huella(&b)}))}
fn tree(root:&Path,dir:&Path,out:&mut Vec<Value>)->R<()>{for e in fs::read_dir(dir)?{let e=e?;let t=e.file_type()?;ck(!t.is_symlink(),"Enlace ajeno al perímetro")?;if t.is_dir(){tree(root,&e.path(),out)?}else{out.push(record(root,&e.path().strip_prefix(root)?.to_string_lossy().replace('\\',"/"))?);}}Ok(())}
fn main()->R<()>{
 let args=std::env::args().collect::<Vec<_>>();let r=Path::new(args.get(1).ok_or("Raíz v3")?);let old=Path::new(args.get(2).ok_or("Fuentes v2")?);
 let p=r.join("precontrol-admision-01");let reg=val(&p.join("REGISTRO.json"))?;
 ck(reg.as_array().is_some_and(|a|a.len()==11&&a.iter().all(|v|v["codigo"]==0)),"Precontrol incompleto")?;
 for v in reg.as_array().unwrap(){let id=v["id"].as_str().ok_or("Operación sin identidad")?;for ch in ["stdout","stderr"]{let b=fs::read(p.join(format!("{id}.{ch}")))?;ck(v[format!("{ch}_sha256")]==huella(&b)&&v[format!("{ch}_bytes")]==b.len(),"Registro previo alterado")?;}}
 let identidad=txt(&p.join("identidad.stdout"))?;ck(identidad.starts_with("00652369-8429-45a8-a287-3bdff932c66e\ngpt-oss-120b\n"),"Instancia distinta")?;
 ck(txt(&p.join("cpu.stdout"))?.trim()=="32","CPU distinta")?;
 ck(identidad.contains("oom 0\n")&&identidad.contains("oom_kill 0\n")&&identidad.ends_with("\n0\n")&&identidad.contains("122406567936\n"),"Memoria, procesos o límite conjunto no conformes")?;
 let available=identidad.lines().find(|l|l.starts_with("MemAvailable:")).ok_or("Memoria disponible ausente")?.split_whitespace().nth(1).ok_or("Valor ausente")?.parse::<u64>()?;ck(available>=120_000_000,"Memoria insuficiente")?;
 ck(txt(&p.join("intercambio.stdout"))?=="0\n0\n","Intercambio no excluido")?;
 let estado=txt(&p.join("estado.stdout"))?;let states=estado.lines().filter(|l|l.starts_with("ActiveState=")).collect::<Vec<_>>();let pids=estado.lines().filter(|l|l.starts_with("MainPID=")).collect::<Vec<_>>();ck(states.len()==7&&pids.len()==7&&states.iter().all(|s|*s=="ActiveState=inactive")&&pids.iter().all(|s|*s=="MainPID=0"),"Procesos propios activos")?;
 let espacio=txt(&p.join("espacio.stdout"))?;let free=espacio.lines().nth(1).ok_or("Espacio ausente")?.split_whitespace().nth(3).ok_or("Espacio incompleto")?.parse::<u64>()?;ck(free>10_737_418_240,"Espacio insuficiente")?;
 let pesos=norm(txt(&p.join("metadatos-modelo.stdout"))?);ck(pesos.len()==27&&pesos==norm(txt(&old.join("precontrol-01/metadatos-pesos.stdout"))?),"Metadatos de pesos distintos")?;
 let initial=val(&old.parent().ok_or("Antecedente")?.join("arbitro-20261002/entrega/MANIFIESTO-PREVIO.json"))?;let hashes=txt(&p.join("nucleo-huellas.stdout"))?;let mut n=0;
 for f in initial["fuentes_y_realizacion"].as_array().ok_or("Fuentes iniciales")?.iter().filter(|v|v["ruta"].as_str().is_some_and(|s|s.starts_with("lenguaje/"))){let rel=f["ruta"].as_str().unwrap();let h=huella(&fs::read(old.join(rel))?);ck(f["sha256"]==h,"Núcleo local modificado")?;ck(hashes.lines().any(|l|l==format!("{h}  /opt/sv-safeguard/arbitro-v2/{rel}")),"Núcleo remoto modificado")?;n+=1;}ck(n==36,"Fuentes del Núcleo incompletas")?;
 ck(fs::read(p.join("parche-numerico.stdout"))?==fs::read(old.join("cotejo-realizacion-01/parche-numerico.stdout"))?,"Motor numérico modificado")?;
 let conductor=txt(&old.join("conductor/src/main.rs"))?.replace("acuerdo(\"carga\",\"N01\",&hash(&serde_json::to_vec(&preparadas[0].tokens)?))?;","acuerdo(\"carga\",\"N02\",&hash(&serde_json::to_vec(&preparadas[1].tokens)?))?;").replace("for (i,caso) in casos.iter().enumerate(){","for (i,caso) in casos.iter().enumerate().skip(1){");
 ck(conductor==txt(&r.join("despliegue/conductor/src/main.rs"))?,"Cambios del conductor exceden comienzo N02")?;
 let remote=txt(&p.join("huellas.stdout"))?;let mut deployed=Vec::new();tree(r,&r.join("despliegue"),&mut deployed)?;
 for f in &deployed{let rel=f["ruta"].as_str().unwrap().strip_prefix("despliegue/").unwrap();let h=f["sha256"].as_str().unwrap();ck(remote.lines().any(|l|l==format!("{h}  /opt/sv-safeguard/arbitro-v3/{rel}")),"Fuente desplegada distinta")?;}
 for (f,h) in [("/opt/sv-safeguard/aislado-v2-r1/bin/mcp","6e47cc556c8acd05d89f81b96f5eacb0e1a629aeaec0326ea3595b3c36941875"),("/opt/sv-safeguard/fuentes/mistral.rs/Cargo.lock","7ee0a0bfb402831a6a8649229672572637f83bbf635919ad5fd3dc744f6b61d8"),("/opt/sv-safeguard/modelo/tokenizer.json","0614fe83cadab421296e664e1f48f4261fa8fef6e03e63bb75c20f38e37d07d3"),("/opt/sv-safeguard/modelo/chat_template.jinja","589c73db2f7775c5f946b84bd4695fd3be3612e48ebb69a956dc38b7ec70236d")]{ck(remote.lines().any(|l|l==format!("{h}  {f}")),"MCP, motor, tokenizador o plantilla distintos")?;}
 let rec=r.join("recuperado-preparacion");let lockold=fs::read(rec.join("fuentes/mistral.rs/Cargo.lock"))?;ck(huella(&lockold)=="7ee0a0bfb402831a6a8649229672572637f83bbf635919ad5fd3dc744f6b61d8","Registro de dependencias recuperado distinto")?;
 let depsold=packages(std::str::from_utf8(&lockold)?)?;let depsnew=packages(&txt(&rec.join("arbitro-v3/conductor/Cargo.lock"))?)?;ck(depsnew.is_subset(&depsold),"Dependencia externa del conductor no conservada")?;
 let archive=fs::read(r.join("preparacion-v3-01.tar.gz"))?;let ah=huella(&archive);ck(txt(&r.join("cotejo-instrumental-01/huellas.stdout"))?.split_whitespace().next()==Some(ah.as_str()),"Archivo de preparación distinto")?;
 let inst=rec.join("evidencias/arbitro3-instrumental-01");let audit=auditar(&inst,false,false)?;ck(audit==val(&r.join("comprobaciones/COTEJO-INSTRUMENTAL-CUSTODIA.json"))?&&audit["emisiones"]==0&&audit["calculos"]==0,"Custodia instrumental no acreditada")?;
 let tokens=val(&rec.join("arbitro-v3/cotejos/INSTRUMENTAL-ENTRADAS.json"))?;ck(tokens["conforme"]==true&&tokens["entradas_prefijadas"]==6&&tokens["emisiones_decodificadas"]==0&&tokens["inferencia"]==false,"Entradas instrumentales no conformes")?;
 let raw=txt(&inst.join("modelo.stdout"))?;ck(tokens["modelo_stdout_sha256"]==huella(raw.as_bytes()),"Cotejo de entradas ajeno al original")?;
 let events=raw.lines().filter_map(|l|l.strip_prefix("SV_EVENT ")).map(serde_json::from_str::<Value>).collect::<Result<Vec<_>,_>>()?;
 let entries=events.iter().filter(|v|v["datos"]["evento"]=="contexto_previsto").map(|v|v["datos"].clone()).collect::<Vec<_>>();ck(json!(entries)==val(&r.join("despliegue/config/ADMISION.json"))?,"Entradas distintas de las prefijadas en v2")?;
 let probe=txt(&r.join("comprobaciones/sonda-mcp-v3.stdout"))?;let pv:Value=serde_json::from_str(probe.trim().strip_prefix("SV_EVENT ").ok_or("Sonda ausente")?)?;
 for s in [&pv["datos"],&events.iter().find(|v|v["datos"]["evento"]=="aislamiento").ok_or("Sonda del conductor ausente")?["datos"]]{ck(s["catalogo_legible"]==true&&s["catalogo_sha256"]=="d2c0613b667c5be47dd6243fab42089a70f19a3bf5d0d1d5d8df1f39097c8c49"&&s["catalogo_escribible"]==false&&s["ruta_externa_legible"]==false&&s["enlace_externo_legible"]==false&&s["custodia_legible"]==false&&s["root_legible"]==false&&s["proxies"]==json!([])&&s["ipv4_error"].as_str().is_some_and(|s|s.contains("97"))&&s["ipv6_error"].as_str().is_some_and(|s|s.contains("97"))&&s["dns_error"].is_string(),"Aislamiento no conforme")?;}
 for (file,counts) in [("comprobaciones/rectificacion-pruebas.stdout",vec![4]),("comprobaciones/instrumentacion-pruebas-01.stdout",vec![4,14,21]),("comprobaciones/recorrido-pruebas-01.stdout",vec![4]),("comprobaciones/control-atomico-pruebas-02.stdout",vec![2]),("recuperado-preparacion/arbitro-v3/compilacion-01/instrumentacion-pruebas.stdout",vec![4,14,21]),("recuperado-preparacion/arbitro-v3/compilacion-01/custodio-pruebas.stdout",vec![4]),("recuperado-preparacion/arbitro-v3/compilacion-01/conductor-pruebas.stdout",vec![6]),("recuperado-preparacion/arbitro-v3/compilacion-02/control-pruebas.stdout",vec![2])]{let text=txt(&r.join(file))?;for c in counts{ck(text.contains(&format!("test result: ok. {c} passed; 0 failed")),"Pruebas Rust no conformes")?;}}
 let resume=val(&r.join("despliegue/config/REANUDACION.json"))?;ck(huella(&fs::read(r.join("despliegue/config/REANUDACION.json"))?)=="348966bc4024fdb71ff6ca8f76a1124a531de3bbb2c9e1da0e657a406b1b4b2e","Reanudación distinta")?;
 let n01=auditar(&old.join("recuperado/puntos/N01"),false,true)?;let adj=fs::read(r.join("entrega/casos/N01/ADJUDICACION.json"))?;ck(resume["cotejo_sha256"]==huella(&serde_json::to_vec(&n01)?)&&resume["evaluacion_sha256"]==huella(&adj),"Referencia de N01 no concordante")?;
 let permissions=val(&r.join("permisos-01/REGISTRO.json"))?;ck(permissions.as_array().is_some_and(|a|a.len()==5&&a.iter().all(|v|v["codigo"]==0)),"Permisos pendientes")?;
 let mut evidence=deployed;
 for rel in ["realizacion/instrumentacion/src/bin/admitir_v3.rs","realizacion/instrumentacion/src/bin/admitir_n01.rs","realizacion/instrumentacion/src/bin/examinar.rs","realizacion/instrumentacion/src/bin/control_paso.rs","comprobaciones/COTEJO-INSTRUMENTAL-CUSTODIA.json","preparacion-v3-01.tar.gz","precontrol-admision-01/REGISTRO.json","precontrol-admision-01/huellas.stdout","precontrol-admision-01/socket.stdout","comprobaciones/sonda-mcp-v3.stdout","entrega/casos/N01/ADJUDICACION.json","recuperacion-entrega-02/COTEJO-DOCUMENTOS-GITHUB.json"]{evidence.push(record(r,rel)?);}
 let report=json!({"expediente":"ARBITRO-SV-SAFEGUARD-20261002/v3","revision_encargo":"a34007b4ddcdac2cc98926830d10612aeabfb318","fijacion_unix_ms":SystemTime::now().duration_since(UNIX_EPOCH)?.as_millis(),"conforme":true,"instancia":"00652369-8429-45a8-a287-3bdff932c66e","modelo":"openai/gpt-oss-safeguard-120b","revision_modelo":"3c7391182603991a904031244e7822488c67796d","motor_revision":"4400935451da5e2dc7379a3f92fbbada66557f6c","nucleo_revision":"1c6b84238e62e867c4d5c5ab8069c9ae8f67dccc","nucleo_archivos_concordantes":n,"nucleo_modificado":false,"motor_numerico_modificado":false,"metadatos_modelo_concordantes":pesos.len(),"dependencias_externas_conservadas":depsnew.len(),"memoria_disponible_kib":available,"espacio_disponible_bytes":free,"realizacion":"arbitro-v3","ejecucion_prevista":"arbitro-continuacion-01","reanudacion":resume,"entradas":tokens["detalle"],"custodia_instrumental":audit,"pruebas_rust":{"locales":49,"servidor":51,"nota":"Ejecuciones identificadas, con pruebas coincidentes entre entornos; no sumar como pruebas distintas ni atribuirlas retrospectivamente a v2."},"limites":{"cargas_adicionales":1,"generaciones_maximas":5,"casos":["N02","N03","N04","N05","N06"],"contexto":8192,"salida_maxima":4096,"reserva_minima":1024,"memoria_conjunta_gib":114,"motor_gib":112,"mcp_mib":512,"custodia_mib":512,"swap":0,"cpu_calculo":"0-29","cpu_administracion":"30-31","registro_mcp_mib":64,"registro_exterior_mib":512,"llamadas":128,"tramas":256},"calculo":{"esfuerzo":"medium","seleccion":"argmax","semilla":42,"pesos":"MXFP4 originales; restantes F32","contexto_nuevo_por_caso":true},"criterio":{"N":6,"formula":"100 * (aciertos - errores_no_criticos) / 6","primer_critico":"cerrar","adjudicacion_previa_al_siguiente":true,"clave_fuera_del_servidor":true,"seis_ceros_posibles":false,"motivo":"N01 conserva un error exclusivamente formal; se completa para diagnóstico conforme a v3 §3."},"archivos":evidence,"huellas_remotas":remote,"recepcion_independiente":"pendiente","autoria_licencia":"© 2026 Juan Antonio Lloret Egea. Algunos derechos reservados. | ORCID: 0000-0002-6634-3351 | Instituto Tecnológico Virtual de la Inteligencia Artificial para el Español™ (ITVIA) | IA eñ™ – La Biblia de la IA™ | ISSN 2695-6411 | Licencia Creative Commons Atribución-NoComercial-SinDerivadas 4.0 Internacional (CC BY-NC-ND 4.0)."});
 save(&r.join("entrega/MANIFIESTO-PREVIO.json"),&report)?;println!("{}",json!({"conforme":true,"nucleo_concordante":n,"dependencias_externas_conservadas":depsnew.len(),"generaciones_admitidas":5,"primer_caso":"N02"}));Ok(())
}
