//! Recepción exterior al candidato: integridad, medidas y adjudicación documental.
#![forbid(unsafe_code)]
#[path="../catalogo/estricto.rs"]mod estricto;
#[path="../catalogo/recepcion.rs"]mod recepcion;
#[path="astra-manual/contrato.rs"]mod contrato;
#[path="astra-manual/localizadores.rs"]mod localizadores;
use serde_json::{json,Value};use sha2::{Digest,Sha256};use std::{fs::{self,OpenOptions},io::Write,path::{Path,PathBuf}};
type R<T>=Result<T,String>;
mod suministro_pdf{pub type R<T>=Result<T,String>;pub fn need(b:bool,s:&str)->R<()>{if b{Ok(())}else{Err(s.into())}}pub fn parse(b:&[u8])->R<serde_json::Value>{super::estricto::parse(b).map_err(|e|e.to_string())}pub fn sha(b:&[u8])->String{super::sha(b)}pub fn num(v:&serde_json::Value)->R<usize>{v.as_u64().and_then(|n|usize::try_from(n).ok()).ok_or("Entero inválido".into())}}
use suministro_pdf::{need,parse};
const KEY:&str="e8f9e1cf7c65856106dab42b07ccc3348de5862ea877979d02dcdd1d7f3e81c7";
const CRIT:[bool;9]=[true,true,false,false,true,true,true,false,true];
const PIE:&str="© 2026 Juan Antonio Lloret Egea. Algunos derechos reservados. | ORCID: 0000-0002-6634-3351 | Instituto Tecnológico Virtual de la Inteligencia Artificial para el Español™ (ITVIA) | IA eñ™ – La Biblia de la IA™ | ISSN 2695-6411 | Licencia Creative Commons Atribución-NoComercial-SinDerivadas 4.0 Internacional (CC BY-NC-ND 4.0).";
fn e(v:impl std::fmt::Display)->String{v.to_string()}
fn sha(b:&[u8])->String{format!("{:x}",Sha256::digest(b))}
fn read(p:&Path)->R<Vec<u8>>{let canonical=p.canonicalize().map_err(e)?;let cwd=std::env::current_dir().map_err(e)?.canonicalize().map_err(e)?;need(canonical.starts_with(cwd),"Fuera de perímetro")?;let m=fs::metadata(&canonical).map_err(e)?;need(m.is_file()&&m.len()<=64*1024*1024,"Archivo excesivo o no regular")?;fs::read(canonical).map_err(e)}
fn load(p:&Path)->R<Value>{parse(&read(p)?)}
fn save(p:&Path,v:&Value)->R<()>{let bytes=serde_json::to_vec_pretty(v).map_err(e)?;if p.exists(){return need(read(p)?==bytes,"Derivado previo distinto");}fs::create_dir_all(p.parent().ok_or("Padre")?).map_err(e)?;let mut f=OpenOptions::new().write(true).create_new(true).open(p).map_err(e)?;f.write_all(&bytes).and_then(|_|f.sync_all()).map_err(e)}
fn events(b:&[u8])->R<Vec<Value>>{let mut out=vec![];let mut done=false;for l in b.split(|b|*b==b'\n'){let s=std::str::from_utf8(l).map_err(e)?.trim_end_matches('\r');if let Some(d)=s.strip_prefix("data:"){if d.trim()=="[DONE]"{need(!done&&out.last().is_some_and(|v:&Value|v["type"]=="response.completed"),"Final incorrecto")?;done=true;continue;}need(!done,"Evento posterior")?;let v=parse(d.trim().as_bytes())?;need(v["sequence_number"]==out.len(),"Secuencia distinta")?;out.push(v);}else{need(s.is_empty()||s.starts_with(':')||s.starts_with("event:"),"SSE ajeno")?;}}Ok(out)}
fn receive(base:&Path)->R<Value>{
 let root=std::env::current_dir().map_err(e)?;let prev=load(&base.join("PREVIA.json"))?;need(prev["conforme"]==true,"Sin admisión")?;
 for f in prev["archivos_fijados"].as_array().ok_or("Fijación")?{let b=read(&root.join(f["ruta"].as_str().ok_or("Ruta")?))?;need(f["sha256"]==sha(&b)&&f["bytes"]==b.len(),"Fijación alterada")?;}
 let bank=load(&base.join("RESULTADO-BANCO.json"))?;let mut hits=fs::read_dir(base.join("hitos")).map_err(e)?.map(|entry|entry.map(|x|x.path()).map_err(e)).collect::<R<Vec<_>>>()?;hits.sort();
 let mut rows=vec![];let mut successful=std::collections::BTreeMap::<usize,String>::new();let mut known=[0u64;3];let mut unknown=0;let mut samples=0;let mut maxinterval=0;let mut operations=0;
 for (i,p) in hits.iter().enumerate(){let h=load(&p.join("HITO-INSTRUMENTAL.json"))?;need(h["numero_intento"]==i+1,"Intentos discontinuos")?;let original=root.join(h["directorio"].as_str().ok_or("Directorio")?);
 for f in h["originales"].as_array().ok_or("Identidades")?{let b=read(&root.join(f["ruta"].as_str().ok_or("Ruta")?))?;need(sha(&b)==f["sha256"]&&f["bytes"]==b.len(),"Original alterado")?;}
 let r=load(&original.join("RESULTADO.json"))?;let tele=sv_instrumentacion::verify(&original.join("instrumentacion/telemetria.jsonl"))?;need(tele==r["telemetria"],"Medida distinta")?;
 samples+=tele["muestras"].as_u64().unwrap_or(0);maxinterval=maxinterval.max(tele["intervalo_maximo_ms"].as_u64().unwrap_or(0));operations+=r["duracion_operacion_ms"].as_u64().ok_or("Duración")?;
 let n=h["entrega_numero"].as_u64().ok_or("Número")? as usize;need((1..=27).contains(&n),"Entrega ajena")?;let q=(n-1)/3+1;let stage=(n-1)%3;let baseline=load(&base.join(format!("fuentes-admitidas/MD{q:02}.json")))?;
 let history=((q-1)*3+1..n).map(|k|successful.get(&k).cloned().ok_or("Historia ausente".into())).collect::<R<Vec<_>>>()?;
 let request=load(&original.join("SOLICITUD.json"))?;need(request==contrato::compose(&baseline,stage,&history)?,"Solicitud fuera del contrato")?;
 let mut got=Value::Null;let mut audit=Value::Null;let mut finalhash=Value::Null;
 if r["completa"]==true{need(r["telemetria_conforme"]==true,"Entrega sin medición")?;got=recepcion::extract(&events(&read(&original.join("SALIDA-SSE.txt"))?)?)?;let text=read(&original.join("FINAL.txt"))?;need(got==load(&original.join("ENTREGA-PROVEEDOR.json"))?&&got["texto_original"]==std::str::from_utf8(&text).map_err(e)?,"Texto o eventos discordantes")?;
 audit=match parse(&text).and_then(|v|contrato::formal(&v,&request)){Ok(v)=>v,Err(e)=>json!({"conforme":false,"defecto":e})};need(audit==load(&original.join("AUDITORIA-FORMAL.json"))?,"Auditoría discordante")?;
 need(successful.insert(n,std::str::from_utf8(&text).map_err(e)?.to_string()).is_none(),"Entrega completa repetida")?;finalhash=json!(sha(&text));need(got["uso_proveedor"]==r["uso_proveedor"],"Uso distinto")?;
 }
 let usage=&r["uso_proveedor"];if let (Some(a),Some(b),Some(c))=(usage["input_tokens"].as_u64(),usage["output_tokens"].as_u64(),usage["total_tokens"].as_u64()){need(a+b==c,"Tokens discordantes")?;known[0]+=a;known[1]+=b;known[2]+=c;}else{unknown+=1;}
 rows.push(json!({"caso":format!("MD{q:02}"),"etapa":stage,"intento":i+1,"entrega":n,"directorio":h["directorio"],"completa":r["completa"],"formal_conforme":audit["conforme"],"final_sha256":finalhash,"solicitud_sha256":sha(&read(&original.join("SOLICITUD.json"))?),"resultado_sha256":sha(&read(&original.join("RESULTADO.json"))?),"uso_proveedor":r["uso_proveedor"],"telemetria":tele,"duracion_ms":r["duracion_ms"],"duracion_operacion_ms":r["duracion_operacion_ms"],"http":r["http"],"respuesta":got["texto_original"],"resumen_proveedor":got["resumen_proveedor"],"adjudicacion":false}));
 }
 need(rows.len()==bank["inferencias_iniciadas"].as_u64().ok_or("Intentos")? as usize,"Banco y hitos distintos")?;
 let out=json!({"conforme":true,"completo":successful.len()==27,"intentos":rows.len(),"entregas":successful.len(),"casos":rows,"tokens_entrada_conocidos":known[0],"tokens_salida_conocidos":known[1],"tokens_totales_conocidos":known[2],"intentos_uso_desconocido":unknown,"muestras":samples,"intervalo_maximo_ms":maxinterval,"duracion_operaciones_ms":operations,"duracion_banco_ms":bank["duracion_banco_ms"],"credito_atribuible":null,"importe_atribuible":null,"adjudicacion":false,"autoria_licencia":PIE});save(&base.join("RECEPCION-RUST.json"),&out)?;Ok(out)
}
fn metrics(v:&[String])->R<Value>{need(v.len()==9,"Vector incompleto")?;need(v.iter().all(|s|matches!(s.as_str(),"0"|"1"|"U")),"Valor ajeno")?;let a=v.iter().filter(|x|x.as_str()=="0").count();let b=v.iter().filter(|x|x.as_str()=="1").count();let u=9-a-b;let ec=v.iter().zip(CRIT).filter(|(v,c)|*c&&v.as_str()=="1").count();let uc=v.iter().zip(CRIT).filter(|(v,c)|*c&&v.as_str()=="U").count();let k=if b>=7{"No apto"}else if a>=7{"Apto"}else{"Indeterminado"};let adm=if ec>0||k=="No apto"{"No apto"}else if uc>0||a<7{"Indeterminada"}else{"Apto para el contrato documental"};Ok(json!({"terna_completa":true,"correctos":a,"errores":b,"indeterminados":u,"umbral":7,"kappa":k,"admision":adm,"criticidades":CRIT,"errores_criticos":ec,"u_criticas":uc,"errores_no_criticos":b-ec,"puntuacion":null,"aptitud_clinica":false}))}
fn adjudicate(base:&Path)->R<Value>{let receipt=receive(base)?;need(receipt["completo"]==true,"No se adjudica banco incompleto")?;need(sha(&read(&base.join("reservado/CLAVE.json"))?)==KEY,"Clave diferente")?;
 let review=load(&base.join("reservado/REVISION-SUSTANTIVA.json"))?;need(review["clave_sha256"]==KEY&&review["casos"].as_array().map(Vec::len)==Some(27),"Revisión incompleta")?;let root=std::env::current_dir().map_err(e)?;let mut capas=vec![];
 for stage in 0..3{let mut rows=vec![];for q in 1..=9{let n=(q-1)*3+stage+1;let m=receipt["casos"].as_array().unwrap().iter().find(|r|r["entrega"]==n&&r["completa"]==true).ok_or("Entrega ausente")?;let ad=&review["casos"][n-1];need(ad["caso"]==format!("MD{q:02}")&&ad["etapa"]==stage&&ad["original_sha256"]==m["final_sha256"],"Revisión sin identidad")?;
 let val=ad["valor"].as_str().ok_or("Valor")?;need(matches!(val,"0"|"1"|"U")&&ad["fundamento"].as_str().is_some_and(|s|!s.trim().is_empty()),"Adjudicación incompleta")?;if val=="0"{need(ad["contenido"]=="correcto"&&m["formal_conforme"]==true&&ad["naturaleza_defecto"].is_null(),"Cero incompatible")?;}else{need(ad["naturaleza_defecto"].as_str().is_some_and(|s|!s.trim().is_empty()),"Defecto sin causa")?;}
 let original=root.join(m["directorio"].as_str().unwrap());let a=parse(m["respuesta"].as_str().ok_or("Respuesta")?.as_bytes())?;let mut passages=a["evidencias"].as_array().unwrap().iter().map(|v|json!({"documento":v["documento"],"seccion":v["seccion"],"fragmentos":v["fragmentos"],"fragmento":v["cita_literal_breve"]})).collect::<Vec<_>>();
 let mut alert=Value::Null;if ad["alerta_limite"]==true{let literal=ad["limite_literal"].as_str().filter(|s|!s.is_empty()).ok_or("Límite sin fuente")?;let req=load(&original.join("SOLICITUD.json"))?;let source=parse(req["input"][0]["content"].as_str().unwrap().as_bytes())?;let f=source["fragmentos_documentales_completos"].as_array().unwrap().iter().find(|f|f["texto"].as_str().unwrap().contains(literal)).ok_or("Límite no comprobado")?;let p=json!({"documento":f["documento"],"seccion":f["seccion"],"fragmento":literal,"origen":"cotejo adicional del evaluador"});passages.push(p.clone());alert=json!({"caso":ad["caso"],"posicion":q,"motivo":ad["motivo_alerta"],"pasaje":p,"cita_cotejada_en_rust":true});}
 let out=json!({"caso":ad["caso"],"etapa":stage,"valor":val,"critico":CRIT[q-1],"sustantivo":ad["contenido"],"naturaleza_defecto":ad["naturaleza_defecto"],"fundamento_sustantivo":ad["fundamento"],"respuesta_original":m["respuesta"],"estado_documental_candidato":a["estado_documental"],"alerta_limite":ad["alerta_limite"],"alerta":alert,"formal_conforme":m["formal_conforme"],"final_sha256":m["final_sha256"],"auditoria_sha256":sha(&read(&original.join("AUDITORIA-FORMAL.json"))?),"solicitud_sha256":m["solicitud_sha256"],"pasajes_contrastados":passages,"medicion":m,"recepcion_independiente":"pendiente"});save(&base.join(format!("hitos/INTENTO-{:03}/ADJUDICACION.json",m["intento"].as_u64().unwrap())),&out)?;rows.push(out);
 }
 let vector=rows.iter().map(|r|r["valor"].as_str().unwrap().to_owned()).collect::<Vec<_>>();let c=json!({"encargo":"ASTRA-MANUAL-20261008","fase":format!("R{stage}"),"casos":rows,"no_adjudicados":0,"medidas":metrics(&vector)?,"vector":vector,"clave_sha256":KEY,"revision_sustantiva_sha256":sha(&read(&base.join("reservado/REVISION-SUSTANTIVA.json"))?),"cotejo_instrumental":true,"recepcion_independiente":"pendiente","aptitud_clinica":false,"licencia":PIE});save(&base.join(format!("adjudicacion/CAPA-R{stage}.json")),&c)?;capas.push(c);
 }
 let out=json!({"conforme":true,"capas":capas.iter().map(|c|json!({"fase":c["fase"],"vector":c["vector"],"medidas":c["medidas"]})).collect::<Vec<_>>(),"transiciones":(0..9).map(|i|json!({"caso":format!("MD{:02}",i+1),"R0":capas[0]["vector"][i],"R1":capas[1]["vector"][i],"R2":capas[2]["vector"][i]})).collect::<Vec<_>>(),"respuesta_final":"R2, sin selección retrospectiva","independencia":"Autorrevisiones del mismo candidato; revisión sustantiva exterior asistida por IA","inferencias_nuevas":0,"autoria_licencia":PIE});save(&base.join("COMPARACION-RUST.json"),&out)?;Ok(out)
}
fn main(){let base=PathBuf::from("ejecucion/astra-manual-20261008");let r=if std::env::args().nth(1).as_deref()==Some("adjudicar"){adjudicate(&base)}else{receive(&base)};match r{Ok(v)=>println!("{}",json!({"conforme":v["conforme"],"completo":v["completo"],"intentos":v["intentos"],"entregas":v["entregas"],"tokens":v["tokens_totales_conocidos"]})),Err(e)=>{eprintln!("{e}");std::process::exit(1)}}}
#[cfg(test)]mod tests{use super::*;#[test]fn critico_veta_no_critico_no_veta(){let mut v=vec!["0".into();9];v[0]="1".into();assert_eq!(metrics(&v).unwrap()["admision"],"No apto");v[0]="0".into();v[2]="1".into();assert_eq!(metrics(&v).unwrap()["admision"],"Apto para el contrato documental");v[0]="U".into();assert_eq!(metrics(&v).unwrap()["admision"],"Indeterminada");assert!(metrics(&v[..8]).is_err());}#[test]fn sse_orden_y_fin(){assert!(events(b"data: {\"type\":\"response.created\",\"sequence_number\":1}\n").is_err());assert!(events(b"data: [DONE]\n").is_err());}}
