use std::{fs::{self,OpenOptions},io::{Read,Write},path::Path,process::Command,time::{SystemTime,UNIX_EPOCH}};
use serde_json::{json,Value};
use sha2::{Digest,Sha256};
type R<T> = Result<T,Box<dyn std::error::Error>>;
const B:&str="/opt/sv-qwen80/examen-09";
const S:&str="/opt/sv-qwen80/examen-09/recuperacion-consulta";
fn save(p:&Path,b:&[u8])->R<()>{let mut f=OpenOptions::new().create_new(true).write(true).open(p)?;f.write_all(b)?;f.sync_all()?;Ok(())}
fn read(p:&Path)->R<Value>{Ok(serde_json::from_slice(&fs::read(p)?)?)}
fn hash(p:&Path)->R<String>{let mut f=fs::File::open(p)?;let mut h=Sha256::new();let mut b=[0;65536];loop{let n=f.read(&mut b)?;if n==0{break}h.update(&b[..n]);}Ok(format!("{:x}",h.finalize()))}
fn cmd(d:&Path,n:&str,exe:&str,args:&[&str])->R<String>{let o=Command::new(exe).args(args).output()?;save(&d.join(format!("{n}.stdout")),&o.stdout)?;save(&d.join(format!("{n}.stderr")),&o.stderr)?;if !o.status.success(){return Err(format!("FALLO:{n}:{:?}",o.status.code()).into())}Ok(String::from_utf8(o.stdout)?)}
fn main()->R<()>{
 if fs::read_to_string("/etc/hostname")?.trim()!="modelos-ia-qwen3-next-80b-a3b-instruct"||fs::read_to_string("/proc/sys/kernel/random/boot_id")?.trim()!="9188529d-a078-4aed-aa91-6794806e1da6"{return Err("IDENTIDAD".into())}
 let root=Path::new(S);let d=root.join("cierre-final");fs::create_dir(&d)?;
 let st=cmd(&d,"estado-previo","systemctl",&["show","sv-qwen80.service","sv-qwen80-examen-09-consulta.service","-p","Id","-p","ActiveState","-p","MainPID","-p","Result","-p","NRestarts","-p","ExecMainStatus","-p","MemoryPeak","-p","RuntimeMaxUSec"])?;
 if st.lines().filter(|s|*s=="MainPID=0").count()!=2||st.lines().filter(|s|*s=="ActiveState=inactive").count()!=2||st.lines().filter(|s|*s=="Result=success").count()!=2{return Err("UNIDADES_NO_CERRADAS".into())}
 let mut residues=vec![];for e in fs::read_dir("/proc")?{let e=e?;let Some(pid)=e.file_name().to_str().and_then(|s|s.parse::<u32>().ok())else{continue};if pid==std::process::id(){continue}if let Ok(exe)=fs::read_link(e.path().join("exe")){if exe.starts_with("/opt/sv-qwen80"){residues.push(json!({"pid":pid,"exe":exe}));}}}save(&d.join("PROCESOS.json"),&serde_json::to_vec_pretty(&residues)?)?;if !residues.is_empty(){return Err("RESIDUOS".into())}
 let close=read(&root.join("recepcion/CIERRE-examen09-20260930-05.json"))?;if close["causa"]!="FIN_CONFORME"||close["custodia_final"]!=true||close["procesos_restantes"].as_array().map(Vec::len)!=Some(0){return Err("GUARDA_NO_CONFORME".into())}
 let run=read(&root.join("evidencias/ejecucion-banco/RESULTADO.json"))?;if run["correcto"]!=true||run["estado_preguntas"]["registros_terminales"]!=25{return Err("BANCO_INCOMPLETO".into())}
 let mut rows=vec![];let mut finals=0;let mut faults=0;for n in 1..=25{let id=format!("P{n:02}");let rp=root.join(format!("recepcion/RESULTADO-{id}.json"));let ap=root.join(format!("recepcion/ADMISION-{id}.json"));let v=read(&rp)?;let a=read(&ap)?;if v["id"]!=id{return Err("ID".into())}let dir=Path::new(v["directorio"].as_str().ok_or("DIRECTORIO")?);if !dir.starts_with(B){return Err("RUTA_EXTERIOR".into())}let mut row=json!({"id":id,"registro":v,"admision":a,"sha256_registro":hash(&rp)?,"sha256_admision":hash(&ap)?});match row["registro"]["resultado"]["estado"].as_str(){Some("terminada")=>{let f=dir.join("FINAL.json");if read(&f)?!=row["registro"]["resultado"]||hash(&f)?!=row["registro"]["resultado_sha256"]{return Err(format!("FINAL_DISCORDANTE:{id}").into())}row["sha256_final"]=json!(hash(&f)?);finals+=1},Some("pendiente_por_impedimento_tecnico")=>faults+=1,_=>return Err(format!("ESTADO:{id}").into())}rows.push(row);}
 if finals!=19||faults!=6{return Err("RECUENTO_DISCORDANTE".into())}save(&d.join("RESULTADOS-COTEJADOS.json"),&serde_json::to_vec_pretty(&json!({"respuestas_finales":finals,"impedimentos_tecnicos":faults,"preguntas_no_ejecutadas":0,"preguntas":rows,"adjudicacion_cientifica":null}))?)?;
 let cfg=root.join("configuracion/preparacion.json");let original=fs::read(&cfg)?;let mut c:Value=serde_json::from_slice(&original)?;if c["run_id"]!="examen09-20260930-05"{return Err("CONFIGURACION".into())}save(&d.join("preparacion-ejecutada.json"),&original)?;c["allow_model_loading"]=json!(false);c["auto_start"]=json!(false);let tmp=root.join("configuracion/preparacion-cierre-final.json");save(&tmp,&serde_json::to_vec_pretty(&c)?)?;fs::rename(tmp,&cfg)?;fs::File::open(cfg.parent().ok_or("PARENT")?)?.sync_all()?;if read(&cfg)?!=c{return Err("CIERRE_CONFIGURACION".into())}
 let kept=cmd(&d,"servicios-conservados","systemctl",&["show","ssh.service","gdm.service","sv-qwen80.socket","-p","Id","-p","ActiveState","-p","MainPID","-p","UnitFileState"])?;if !kept.contains("UnitFileState=masked"){return Err("SOCKET_NO_ENMASCARADO".into())}
 cmd(&d,"diario","journalctl",&["-u","sv-qwen80.service","-u","sv-qwen80-examen-09-consulta.service","--since","2026-09-30 16:46:00 UTC","--no-pager","-o","short-iso-precise"])?;
 cmd(&d,"red","ss",&["-ltnp"])?;cmd(&d,"memoria","cat",&["/proc/meminfo","/proc/swaps"])?;
 save(&d.join("CIERRE-COMPROBADO.json"),&serde_json::to_vec_pretty(&json!({"utc_ms":SystemTime::now().duration_since(UNIX_EPOCH)?.as_millis(),"segmento":"examen09-20260930-05","respuestas_finales":finals,"impedimentos_tecnicos":faults,"registros_terminales":25,"carga_deshabilitada":true,"procesos_propios_restantes":[],"guarda":close,"instancia_conservada":true,"adjudicacion_cientifica":null}))?)?;
 println!("CIERRE_COMPROBADO: 19 respuestas finales; 6 impedimentos; 25 registros; carga deshabilitada; instancia conservada");Ok(())
}
