//! Publicación y cotejo de archivos explícitos; conserva main y rechaza avances concurrentes.
mod recibido {
 use std::{io::Write,fs::OpenOptions,path::{Path,Component}};
 type R<T>=Result<T,Box<dyn std::error::Error>>;
 const K:[u32;64]=[0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2];
 pub fn hash(bytes:&[u8])->String{let mut p=bytes.to_vec();let bits=(p.len()as u64)*8;p.push(0x80);while p.len()%64!=56{p.push(0)}p.extend(bits.to_be_bytes());let mut h=[0x6a09e667u32,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19];
 for c in p.chunks_exact(64){let mut w=[0u32;64];for i in 0..16{w[i]=u32::from_be_bytes(c[i*4..i*4+4].try_into().unwrap())}for i in 16..64{let a=w[i-15];let b=w[i-2];w[i]=w[i-16].wrapping_add(a.rotate_right(7)^a.rotate_right(18)^(a>>3)).wrapping_add(w[i-7]).wrapping_add(b.rotate_right(17)^b.rotate_right(19)^(b>>10));}let[mut a,mut b,mut c,mut d,mut e,mut f,mut g,mut hh]=h;for i in 0..64{let t1=hh.wrapping_add(e.rotate_right(6)^e.rotate_right(11)^e.rotate_right(25)).wrapping_add((e&f)^(!e&g)).wrapping_add(K[i]).wrapping_add(w[i]);let t2=(a.rotate_right(2)^a.rotate_right(13)^a.rotate_right(22)).wrapping_add((a&b)^(a&c)^(b&c));hh=g;g=f;f=e;e=d.wrapping_add(t1);d=c;c=b;b=a;a=t1.wrapping_add(t2)}for(i,v)in[a,b,c,d,e,f,g,hh].into_iter().enumerate(){h[i]=h[i].wrapping_add(v)}}h.iter().map(|n|format!("{n:08x}")).collect()}
 pub fn encode(b:&[u8])->String{let t=b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";let mut o=String::with_capacity(b.len().div_ceil(3)*4);for p in b.chunks(3){let n=((p[0]as u32)<<16)|((p.get(1).copied().unwrap_or(0)as u32)<<8)|(p.get(2).copied().unwrap_or(0)as u32);o.push(t[(n>>18)as usize]as char);o.push(t[((n>>12)&63)as usize]as char);o.push(if p.len()>1{t[((n>>6)&63)as usize]as char}else{'='});o.push(if p.len()>2{t[(n&63)as usize]as char}else{'='});}o}
 pub fn guardar(p:&str,b:&[u8])->R<()>{let p=Path::new(p);if p.is_absolute()||p.components().any(|c|matches!(c,Component::ParentDir)){return Err("Destino exterior".into())}let mut f=OpenOptions::new().write(true).create_new(true).open(p)?;f.write_all(b)?;f.sync_all()?;Ok(())}
}
use std::{fs,io::Write,path::Path,process::{Command,Stdio}};
type R<T>=Result<T,Box<dyn std::error::Error>>;
fn q(s:&str)->String{let mut o=String::from("\"");for c in s.chars(){match c{'"'=>o.push_str("\\\""),'\\'=>o.push_str("\\\\"),'\n'=>o.push_str("\\n"),'\r'=>o.push_str("\\r"),'\t'=>o.push_str("\\t"),c if c<' '=>o.push_str(&format!("\\u{:04x}",c as u32)),_=>o.push(c)}}o.push('"');o}
fn bytes(p:&str)->R<Vec<u8>>{let path=Path::new(p).canonicalize()?;if !path.starts_with(std::env::current_dir()?.canonicalize()?)||fs::metadata(&path)?.len()>64*1024*1024{return Err("Archivo exterior o fuera de cota".into())}Ok(fs::read(path)?)}
fn api(endpoint:&str,method:&str,body:Option<&str>,jq:&str)->R<String>{let mut c=Command::new("gh");c.args(["api",endpoint,"--method",method,"--jq",jq]);if body.is_some(){c.args(["--input","-"]);}let mut child=c.stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(Stdio::piped()).spawn()?;if let Some(s)=body{child.stdin.take().ok_or("stdin")?.write_all(s.as_bytes())?;}let o=child.wait_with_output()?;if !o.status.success(){std::io::stderr().write_all(&o.stderr)?;return Err(format!("GitHub: {method} {endpoint}; código {:?}",o.status.code()).into())}Ok(String::from_utf8(o.stdout)?.trim().to_owned())}
fn decode(s:&str)->R<Vec<u8>>{let t=b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";let mut out=vec![];let mut b=0u32;let mut n=0;let mut pad=false;for c in s.bytes(){if c.is_ascii_whitespace(){continue}if c==b'='{pad=true;continue}if pad{return Err("Base64 inválido".into())}let v=t.iter().position(|x|*x==c).ok_or("Base64")?as u32;b=(b<<6)|v;n+=6;if n>=8{n-=8;out.push((b>>n)as u8);b&=(1<<n)-1;}}if b!=0{return Err("Bits residuales".into())}Ok(out)}
fn entries(file:&str,repo:&str)->R<Vec<(String,String)>>{if !["juantoniolloretegea/SV-sala-de-maquinas","juantoniolloretegea/SV-motor"].contains(&repo){return Err("Repositorio no autorizado".into())}let mut set=std::collections::BTreeSet::new();let mut out=vec![];for l in std::str::from_utf8(&bytes(file)?)?.lines(){let f:Vec<_>=l.split('\t').collect();if f.len()!=2||f[1].contains("..")||!set.insert(f[1].to_owned()){return Err("Lista inválida".into())}let ok=if repo.ends_with("SV-sala-de-maquinas"){f[1].starts_with("respuestas-ejecucion/QWEN80-Q4K-ONECLOUD-20260929/entrega-09/")}else{["laboratorio/ensayo-ia-y-observabilidad/modelos-de-ia/qwen/qwen3-next-80b-a3B-instruct/REGISTRO-INSTALACION-20260929.md","laboratorio/ensayo-ia-y-observabilidad/modelos-de-ia/qwen/qwen3-next-80b-a3B-instruct/REGISTRO-INSTALACION-20260929.json"].contains(&f[1])};if !ok{return Err("Ruta no autorizada".into())}bytes(f[0])?;out.push((f[0].into(),f[1].into()));}Ok(out)}
fn verify(repo:&str,commit:&str,list:&[(String,String)],record:&str)->R<()>{let mut rows=vec![];for(local,remote)in list{let b=bytes(local)?;let blob=api(&format!("repos/{repo}/contents/{remote}?ref={commit}"),"GET",None,".sha")?;let received=decode(&api(&format!("repos/{repo}/git/blobs/{blob}"),"GET",None,".content")?)?;if received!=b{return Err(format!("Cotejo discordante: {remote}").into())}rows.push(format!("{{\"ruta\":{},\"bytes\":{},\"sha256\":{},\"git_blob\":{},\"identidad_bytes\":true}}",q(remote),b.len(),q(&recibido::hash(&b)),q(&blob)));println!("COTEJO_CONFORME {remote}");}let report=format!("{{\"repositorio\":{},\"commit\":{},\"archivos\":[{}],\"cotejo_completo\":true}}",q(repo),q(commit),rows.join(","));recibido::guardar(record,report.as_bytes())?;Ok(())}
fn main()->R<()>{let a:Vec<_>=std::env::args().collect();if std::env::current_dir()?.file_name().and_then(|p|p.to_str())!=Some("entrega-09"){return Err("Directorio no autorizado".into())}match a.get(1).map(String::as_str){
 Some("comprobar")=>{assert_eq!(recibido::hash(b""),"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855");assert_eq!(recibido::hash(b"abc"),"ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad");assert_eq!(recibido::hash(&vec![b'a';1_000_000]),"cdc76e5c9914fb9281a1c7e284d73e67f1809a48a497200e046d39ccc7112cd0");for (b,s)in [(b"f".as_slice(),"Zg=="),(b"fo".as_slice(),"Zm8="),(b"foo".as_slice(),"Zm9v")]{assert_eq!(recibido::encode(b),s);assert_eq!(decode(s)?,b);}println!("Vectores SHA-256 y Base64 conformes");},
 Some("hash")=>for p in a.iter().skip(2){let b=bytes(p)?;println!("{}\t{}\t{p}",recibido::hash(&b),b.len())},
 Some("fragmentar")=>{let b=bytes(&a[2])?;let mut restored=vec![];for(i,part)in b.chunks(20*1024*1024).enumerate(){let p=format!("{}.parte-{:03}",a[2],i+1);recibido::guardar(&p,part)?;let r=bytes(&p)?;if r!=part{return Err("Fragmento discordante".into())}restored.extend(r);println!("{}\t{}\t{p}",recibido::hash(part),part.len());}if restored!=b{return Err("Recomposición discordante".into())}println!("RECOMPOSICION_CONFORME {} {}",recibido::hash(&b),b.len());},
 Some("verificar") if a.len()==6=>{let list=entries(&a[4],&a[2])?;verify(&a[2],&a[3],&list,&a[5])?;},
 Some("publicar") if a.len()==7=>{let repo=&a[2];let expected=&a[3];if expected.len()!=40||!expected.bytes().all(|b|b.is_ascii_hexdigit()){return Err("Referencia no fijada".into())}let list=entries(&a[4],repo)?;let ref_url=format!("repos/{repo}/git/ref/heads/main");if api(&ref_url,"GET",None,".object.sha")?!=*expected{return Err("Avance concurrente: revisar antes de publicar".into())}let base=api(&format!("repos/{repo}/git/commits/{expected}"),"GET",None,".tree.sha")?;let mut nodes=vec![];
 for(local,remote)in &list{let b=bytes(local)?;let payload=format!("{{\"encoding\":\"base64\",\"content\":{}}}",q(&recibido::encode(&b)));let blob=api(&format!("repos/{repo}/git/blobs"),"POST",Some(&payload),".sha")?;nodes.push(format!("{{\"path\":{},\"mode\":\"100644\",\"type\":\"blob\",\"sha\":{}}}",q(remote),q(&blob)));println!("OBJETO_CONSERVADO {remote}");}
 let tree=api(&format!("repos/{repo}/git/trees"),"POST",Some(&format!("{{\"base_tree\":{},\"tree\":[{}]}}",q(&base),nodes.join(","))),".sha")?;let commit=api(&format!("repos/{repo}/git/commits"),"POST",Some(&format!("{{\"message\":{},\"tree\":{},\"parents\":[{}]}}",q(&a[6]),q(&tree),q(expected))),".sha")?;
 if api(&ref_url,"GET",None,".object.sha")?!=*expected{return Err(format!("Avance concurrente; commit preparado pero no publicado: {commit}").into())}let actual=api(&format!("repos/{repo}/git/refs/heads/main"),"PATCH",Some(&format!("{{\"sha\":{},\"force\":false}}",q(&commit))),".object.sha")?;if actual!=commit{return Err("Referencia publicada discordante".into())}recibido::guardar(&format!("{}-PUBLICADO.json",a[5]),format!("{{\"repositorio\":{},\"commit\":{},\"padre\":{},\"force\":false,\"cotejo_pendiente\":true}}",q(repo),q(&commit),q(expected)).as_bytes())?;println!("PUBLICADO {commit}");verify(repo,&commit,&list,&format!("{}-COTEJADO.json",a[5]))?;},
 _=>return Err("Uso: hash archivos | fragmentar archivo | publicar repo commit lista registro mensaje | verificar repo commit lista registro".into())}Ok(())}
