//! Registro derivado de servicio; sin solicitudes al proveedor.
#![forbid(unsafe_code)]
use serde_json::{json,Value};use sha2::{Digest,Sha256};use std::{fs,path::Path};
fn read(p:&Path)->Result<Value,Box<dyn std::error::Error>>{Ok(serde_json::from_slice(&fs::read(p)?)?)}
fn h(p:&Path)->Result<String,Box<dyn std::error::Error>>{Ok(format!("{:x}",Sha256::digest(fs::read(p)?)))}
fn projection(a:&Value)->Value{json!({"caso":a["caso"],"revision":a["revision"],"completa":a["completa"],"inicio_envio_utc_ms":a["inicio_envio_utc_ms"],"fin_operacion_utc_ms":a["fin_operacion_utc_ms"],"duracion_operacion_ms":a["duracion_operacion_ms"],"resultado_sha256":a["resultado_sha256"],"sse_sha256":a["sse_sha256"]})}
fn main()->Result<(),Box<dyn std::error::Error>>{
 let base=Path::new("ejecucion/astra-examen25-conjunto-20261007");let a=read(&base.join("INTENTOS-CONSUMO-RUST.json"))?;let s=read(&base.join("SERVICIO-PROVEEDOR-RUST.json"))?;let m=read(&base.join("METRICAS-RUST.json"))?;let rows=a["casos"].as_array().ok_or("Intentos ausentes")?;
 assert_eq!(rows.len(),77);assert_eq!(s["entregas_completas"],75);assert_eq!(m["conforme"],true);
 let find=|r:&str,c:&str|->Result<&Value,Box<dyn std::error::Error>>{let v=rows.iter().filter(|v|v["revision"]==r&&v["caso"]==c).collect::<Vec<_>>();if v.len()!=1{return Err("Identidad no única".into())}Ok(v[0])};
 let failed=find("r2","P15-R0")?;assert_eq!(failed["completa"],false);assert_eq!(failed["error_proveedor"]["code"],"server_is_overloaded");assert_eq!(failed["medicion"]["uso"]["total_tokens"],Value::Null);
 let recovered=find("r3","P16-R0")?;assert_eq!(recovered["completa"],true);let final_q=(0..3).map(|n|{let v=find("r3",&format!("P15-R{n}"))?;assert_eq!(v["completa"],true);Ok(projection(v))}).collect::<Result<Vec<_>,Box<dyn std::error::Error>>>()?;
 let out=json!({"id":"SV-SERVICIO-OPENAI-20261007-001","proveedor":"OpenAI","modelo":"gpt-6-astra","suceso":"S39","tiques":["TT-0016","TT-0021"],"examen":"ASTRA-EXAMEN25-20261007","clasificacion":"interrupcion_comunicada_por_el_proveedor","hecho":projection(failed),"argumento_proveedor":failed["error_proveedor"],"latencia_hasta_error_ms":failed["latencia_error_ms"],"duracion_total_indisponibilidad_ms":null,"alcance_no_entregado":"Respuesta inicial P15/R0; sus dos revisiones dependientes quedaron pendientes. Las 42 entregas completas anteriores se conservaron.","uso_intento_interrumpido":failed["medicion"]["uso"],"recuperacion_servicio_observada":projection(recovered),"recuperacion_pregunta":final_q,"intervencion_local":"La pausa de recepción y corrección del receptor no acredita indisponibilidad continua del proveedor. La causa local secundaria se conserva separadamente.","causa_receptor_secundaria":failed["causa_receptor_local"],"regla_continuidad":{"aplicar_desde":"adenda r3 autorizada durante la interrupción","aplazar_pregunta":true,"ventana_operativa_ms":300000,"al_agotar":"prueba no válida por falta de recursos que garanticen el examen","alcanzada_en_r3":false,"puntuacion_candidato_por_fallo_servicio":null},"marco_normativo":{"referencias_principales":[{"norma":"ISO/IEC 42001:2023","url":"https://www.iso.org/standard/42001"},{"norma":"ISO 9001:2026","url":"https://www.iso.org/standard/88464.html","publicacion":"2026-09-16"}],"complementarias":["ISO/IEC 20000-1:2018","ISO/IEC 25010:2023"],"alcance":"Referencias para gestión y evaluación posterior; no declara certificación, conformidad integral ni incumplimiento de cláusulas no auditadas"},"puntuacion_proveedor":null,"estado":"Entrega recuperada; evaluación del servicio pendiente","fuentes":{"intentos_sha256":h(&base.join("INTENTOS-CONSUMO-RUST.json"))?,"servicio_sha256":h(&base.join("SERVICIO-PROVEEDOR-RUST.json"))?},"autoria_licencia":m["autoria_licencia"]});
 let dest=base.join("REGISTRO-OPENAI-20261007-001.json");fs::write(dest,serde_json::to_vec_pretty(&out)?)?;println!("Incidencia y recuperación cotejadas: SV-SERVICIO-OPENAI-20261007-001");Ok(())
}
