//! Recuperación desde P23 tras el rechazo íntegro de la búsqueda emitida en P22.
use crate::{Result,store,control::functional::{read,durable},recovery::{ItemCode,ItemFault}};
use serde_json::{Value,json};
use std::{fs,path::Path,io::Write};
use sv_mcp_documental::{sha256,parse_strict};
pub const RUN:&str="examen09-20260930-05";
pub const OLD:&str="/opt/sv-qwen80/examen-09/recuperacion-parametros/recepcion";
pub const NEW:&str="/opt/sv-qwen80/examen-09/recuperacion-consulta/recepcion";
pub const P22:&str="/opt/sv-qwen80/examen-09/recuperacion-parametros/recepcion/examen09-20260930-04/consulta-2651";
const RAW_SHA:&str="918aa5fb26e2197331ea9516fec5273c4cf947538621937fa10642025a0a7664";
const SSE_SHA:&str="118936b36dc50efd89ce43dd15b2f3d638f7aff13b7f909b3b1d9025bf31787b";
const DEADLINE_SHA:&str="fcc942d3249f852c03c240795243c47aec791cde6463a195f863c0fa96b82011";
fn copy(src:&Path,dst:&Path)->Result<Value>{let b=fs::read(src)?;let mut f=fs::OpenOptions::new().create_new(true).write(true).open(dst)?;f.write_all(&b)?;f.sync_all()?;fs::File::open(dst.parent().ok_or("PADRE")?)?.sync_all()?;if fs::read(dst)?!=b{return Err("COPIA_DISCORDANTE".into())}Ok(json!({"origen":src,"destino":dst,"sha256":sha256(&b),"bytes":b.len()}))}
fn requests(dir:&Path,rows:&mut Vec<Value>)->Result<()>{for e in fs::read_dir(dir)?{let e=e?;let t=e.file_type()?;if t.is_symlink(){return Err("ENLACE_EN_CUSTODIA".into())}if t.is_dir(){requests(&e.path(),rows)?}else if e.file_name()=="SOLICITUD.json"{rows.push(parse_strict(&fs::read(e.path())?)?)}}Ok(())}
pub fn proof()->Result<Value>{
 let p=Path::new(P22);let raw=fs::read(p.join("01-GENERACION-EMISION.bin"))?;let sse=fs::read(p.join("01-GENERACION-ORIGINAL.sse"))?;
 if sha256(&raw)!=RAW_SHA||sha256(&sse)!=SSE_SHA{return Err("ORIGINALES_P22_DISCORDANTES".into())}
 let mut assembled=vec![];let mut done=false;let mut finish=false;
 for line in std::str::from_utf8(&sse)?.lines(){if let Some(d)=line.strip_prefix("data: "){if d=="[DONE]"{done=true;continue}let v=parse_strict(d.as_bytes())?;if v.get("error").is_some(){return Err("ERROR_MOTOR_ORIGINAL".into())}for c in v["choices"].as_array().ok_or("CHOICES")?{if c["index"]!=0{return Err("SECUENCIA_DISTINTA".into())}if let Some(b)=c["logprobs"]["bytes"].as_array(){for n in b{assembled.push(u8::try_from(n.as_u64().ok_or("BYTE")?)?)}}if c["finish_reason"]=="tool_calls"{finish=true}}}}
 if !done||!finish||assembled!=raw{return Err("EMISION_P22_NO_COTEJADA".into())}
 let err=crate::query::parsed_calls(&raw).err().ok_or("RECHAZO_AUSENTE")?;
 if err.downcast_ref::<ItemFault>().map(|f|f.0)!=Some(ItemCode::SearchQueryBounds){return Err(err)}
 let original=read(&p.join("ERROR.json"))?;if original["cadena"][0]["texto"]!="CONSULTA_FUERA_DE_COTA"||!original["instrumento"].is_null(){return Err("CAUSA_ORIGINAL_DISTINTA".into())}
 let a=read(&Path::new(OLD).join("ADMISION-P22.json"))?;crate::examen::validate_request(&a["entrada"])?;
 if read(&p.join("EXAMEN.json"))?!=a["entrada"]||p.join("FINAL.json").exists()||Path::new(OLD).join("RESULTADO-P22.json").exists(){return Err("ADMISION_O_RESULTADO_P22_DISCORDANTE".into())}
 let mut req=vec![];requests(&p.join("mcp"),&mut req)?;if req.len()!=1||req[0]["method"]!="tools/list"{return Err("EFECTOS_MCP_NO_PREVISTOS".into())}
 Ok(json!({"utc_ms":store::now(),"id":"P22","emision_sha256":sha256(&raw),"sse_sha256":sha256(&sse),"emision_original":std::str::from_utf8(&raw)?,"error_original":original,"error_instrumental":crate::continuation::error(err.as_ref()),"solicitudes_mcp":req,"llamadas_documentales_ejecutadas":0,"reparacion_de_argumentos":false,"cota_modificada":false}))
}
fn deadline(base:&Path)->Result<()>{let b=fs::read(base.join("CAMPANA.json"))?;if sha256(&b)!=DEADLINE_SHA||b!=fs::read("/opt/sv-qwen80/examen-09/recepcion/CAMPANA.json")?{return Err("PLAZO_ORIGINAL_MODIFICADO".into())}let v=parse_strict(&b)?;crate::completion_policy::campaign(&v)?;Ok(())}
fn validate_prior()->Result<()>{let old=Path::new(OLD);deadline(old)?;if crate::examen::count(old)?!=22{return Err("ADMISIONES_DISTINTAS".into())}for n in 1..=22{let a=read(&old.join(format!("ADMISION-P{n:02}.json")))?;crate::examen::validate_request(&a["entrada"])?;if n==22{continue}let r=read(&old.join(format!("RESULTADO-P{n:02}.json")))?;if r["resultado_sha256"]!=sha256(&serde_json::to_vec(&r["resultado"])?)||!r["adjudicacion_independiente"].is_null(){return Err("RESULTADO_PREVIO_MODIFICADO".into())}match n{9|12|14|15|20=>{let expected=match n{9=>"MULTIPLE_DOCUMENT_CALLS",15=>"MALFORMED_PARAMETERS",_=>"CONTEXT_LIMIT"};if r["resultado"]["estado"]!="pendiente_por_impedimento_tecnico"||r["resultado"]["respuesta_final_obtenida"]!=false||r["resultado"]["codigo_instrumental"]!=expected{return Err("IMPEDIMENTO_PREVIO_DISTINTO".into())}},_=>{let dir=Path::new(r["directorio"].as_str().ok_or("DIRECTORIO")?);if r["resultado"]["estado"]!="terminada"||read(&dir.join("FINAL.json"))?!=r["resultado"]{return Err("FINAL_PREVIO_NO_COTEJADO".into())}}}}Ok(())}
pub fn verify_resume(base:&Path)->Result<()>{deadline(base)?;let v=read(&base.join("RECUPERACION.json"))?;if v["adenda_commit"]!=crate::recovery::ADDENDUM||v["nuevo_segmento"]!=RUN||v["siguiente"]!="P23"||crate::examen::count(base)?!=22{return Err("RECUPERACION_P23_DISCORDANTE".into())}for n in 1..=22{let a=format!("ADMISION-P{n:02}.json");if fs::read(base.join(&a))?!=fs::read(Path::new(OLD).join(a))?{return Err("ADMISION_MODIFICADA".into())}if n<22{let r=format!("RESULTADO-P{n:02}.json");if fs::read(base.join(&r))?!=fs::read(Path::new(OLD).join(r))?{return Err("RESULTADO_MODIFICADO".into())}}}let p=read(&base.join("RESULTADO-P22.json"))?;let actual=proof()?;let preserved=&p["procedencia"]["comprobacion"];let expected=crate::recovery::terminal(&preserved["error_instrumental"])?;if p["resultado"]!=expected||expected["codigo_instrumental"]!="SEARCH_QUERY_BOUNDS"||preserved["error_original"]!=actual["error_original"]||preserved["emision_sha256"]!=RAW_SHA||preserved["sse_sha256"]!=SSE_SHA||!p["adjudicacion_independiente"].is_null()||p["resultado_sha256"]!=sha256(&serde_json::to_vec(&p["resultado"])?) {return Err("TERMINAL_P22_DISCORDANTE".into())}Ok(())}
pub fn prepare()->Result<()>{validate_prior()?;let evidence=proof()?;let old=Path::new(OLD);let new=Path::new(NEW);fs::create_dir(new)?;let mut copies=vec![copy(&old.join("CAMPANA.json"),&new.join("CAMPANA.json"))?];for n in 1..=22{let a=format!("ADMISION-P{n:02}.json");copies.push(copy(&old.join(&a),&new.join(a))?);if n<22{let r=format!("RESULTADO-P{n:02}.json");copies.push(copy(&old.join(&r),&new.join(r))?);}}let result=crate::recovery::terminal(&evidence["error_instrumental"])?;durable(&new.join("RESULTADO-P22.json"),&json!({"id":"P22","directorio":P22,"resultado":result,"resultado_sha256":sha256(&serde_json::to_vec(&result)?),"utc_ms":store::now(),"adjudicacion_independiente":null,"procedencia":{"tipo":"registro_terminal_posterior_al_cierre_original","adenda_commit":crate::recovery::ADDENDUM,"comprobacion":evidence}}))?;durable(&new.join("RECUPERACION.json"),&json!({"utc_ms":store::now(),"adenda_commit":crate::recovery::ADDENDUM,"anterior":"examen09-20260930-04","nuevo_segmento":RUN,"siguiente":"P23","copias":copies,"estado":crate::recovery::counts(new)?,"plazo_ampliado":false}))?;verify_resume(new)?;println!("{}",crate::recovery::counts(new)?);Ok(())}
#[cfg(test)]mod tests{
 use super::*;
 #[test]fn original_p22_rechazado_sin_efecto(){validate_prior().unwrap();let v=proof().unwrap();assert_eq!(v["llamadas_documentales_ejecutadas"],0);assert_eq!(v["cota_modificada"],false);}
 #[test]fn solo_error_tipificado_es_local(){for s in ["CONSULTA_FUERA_DE_COTA","SEARCH_QUERY_BOUNDS","FALLO_MOTOR","CUSTODIA","NORMALIZACION_MODIFICA_LLAMADA","AISLAMIENTO_NO_CONFORME"]{let e:Box<dyn std::error::Error>=s.into();assert!(!crate::examen::item_error(&crate::continuation::error(e.as_ref())))}assert!(crate::examen::item_error(&crate::continuation::error(ItemCode::SearchQueryBounds.fault().as_ref())));}
 #[test]fn admisiones_p23_sin_repetir(){let root=std::env::temp_dir().join(store::id("consulta-admision"));fs::create_dir(&root).unwrap();for n in 1..=22{let a=format!("ADMISION-P{n:02}.json");copy(&Path::new(OLD).join(&a),&root.join(a)).unwrap();if n<22{let r=format!("RESULTADO-P{n:02}.json");copy(&Path::new(OLD).join(&r),&root.join(r)).unwrap();}}assert!(crate::examen::admit(&root,RUN,&crate::examen::request("P23").unwrap()).is_err());let t=crate::recovery::terminal(&crate::continuation::error(ItemCode::SearchQueryBounds.fault().as_ref())).unwrap();durable(&root.join("RESULTADO-P22.json"),&json!({"resultado":t})).unwrap();let c=crate::recovery::counts(&root).unwrap();assert_eq!(c["respuestas_completas"],16);assert_eq!(c["preguntas_con_impedimento"],6);for n in 1..=22{assert!(crate::examen::admit(&root,RUN,&crate::examen::request(&format!("P{n:02}")).unwrap()).is_err())}crate::examen::admit(&root,RUN,&crate::examen::request("P23").unwrap()).unwrap();assert!(crate::examen::admit(&root,RUN,&crate::examen::request("P23").unwrap()).is_err());fs::remove_dir_all(root).unwrap();}
}
