//! Conservación del tercer segmento y preparación controlada de P16-P25.
use std::{fs::{self,OpenOptions},io::{Read,Write},path::Path,process::Command,time::{SystemTime,UNIX_EPOCH,Instant,Duration},os::unix::{fs::PermissionsExt,net::UnixStream}};
use serde_json::{Value,json};use sha2::{Sha256,Digest};
type R<T>=Result<T,Box<dyn std::error::Error>>;
const BASE:&str="/opt/sv-qwen80/examen-09";const OLD:&str="/opt/sv-qwen80/examen-09/recuperacion-contexto";const NEW:&str="/opt/sv-qwen80/examen-09/recuperacion-parametros";const RUN:&str="examen09-20260930-04";const DRIVER:&str="sv-qwen80-examen-09-parametros.service";
fn now()->u128{SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_millis()}
fn hash(b:&[u8])->String{format!("{:x}",Sha256::digest(b))}
fn save(p:&Path,b:&[u8])->R<()>{let mut f=OpenOptions::new().create_new(true).write(true).open(p)?;f.write_all(b)?;f.sync_all()?;fs::File::open(p.parent().ok_or("PADRE")?)?.sync_all()?;Ok(())}
fn read(p:impl AsRef<Path>)->R<Value>{Ok(serde_json::from_slice(&fs::read(p)?)?)}
fn command(d:&Path,n:&str,exe:&str,args:&[&str])->R<Vec<u8>>{save(&d.join(format!("{n}-ORDEN.json")),&serde_json::to_vec(&json!({"utc_ms":now(),"programa":exe,"argumentos":args}))?)?;let o=Command::new(exe).args(args).output()?;save(&d.join(format!("{n}.stdout")),&o.stdout)?;save(&d.join(format!("{n}.stderr")),&o.stderr)?;save(&d.join(format!("{n}-RESULTADO.json")),&serde_json::to_vec(&json!({"codigo":o.status.code(),"correcto":o.status.success(),"utc_ms":now()}))?)?;if !o.status.success(){return Err(format!("ORDEN_ADVERSA:{n}:{}",String::from_utf8_lossy(&o.stderr)).into())}Ok(o.stdout)}
fn identity()->R<()>{if fs::read_to_string("/etc/hostname")?.trim()!="modelos-ia-qwen3-next-80b-a3b-instruct"||fs::read_to_string("/proc/sys/kernel/random/boot_id")?.trim()!="9188529d-a078-4aed-aa91-6794806e1da6"{return Err("IDENTIDAD_DISCORDANTE".into())}Ok(())}
fn remaining()->R<u64>{let b=fs::read(format!("{BASE}/recepcion/CAMPANA.json"))?;if hash(&b)!="fcc942d3249f852c03c240795243c47aec791cde6463a195f863c0fa96b82011"{return Err("PLAZO_DISCORDANTE".into())}let p:Value=serde_json::from_slice(&b)?;let mono=(fs::read_to_string("/proc/uptime")?.split_whitespace().next().ok_or("MONO")?.parse::<f64>()?*1000.)as u64;let left=p["plazo_global_utc_ms"].as_u64().ok_or("UTC")?.saturating_sub(now()as u64).min(p["plazo_global_mono_ms"].as_u64().ok_or("MONO")?.saturating_sub(mono));left.checked_sub(90000).map(|n|n/1000).filter(|n|*n>600).ok_or_else(||"PLAZO_INSUFICIENTE".into())}
fn stopped(d:&Path)->R<()> {let o=command(d,"estado-previo","systemctl",&["show","sv-qwen80.service","sv-qwen80-examen-09-contexto.service","-p","Id","-p","MainPID","-p","ActiveState","-p","Result","-p","ExecMainStatus"])?;let s=std::str::from_utf8(&o)?;if s.lines().filter(|s|*s=="MainPID=0").count()!=2||s.lines().any(|s|s=="ActiveState=active"||s=="ActiveState=activating"){return Err("PROCESOS_ACTIVOS".into())}for e in fs::read_dir("/proc")?{let e=e?;let Some(pid)=e.file_name().to_str().and_then(|s|s.parse::<u32>().ok())else{continue};if pid==std::process::id(){continue}match fs::read_link(e.path().join("exe")){Ok(p)=>{if p.starts_with(format!("{BASE}/bin"))||p.starts_with(format!("{OLD}/bin"))||p.starts_with(format!("{NEW}/bin")){return Err(format!("RESIDUO:{pid}:{}",p.display()).into())}},Err(e)if e.kind()==std::io::ErrorKind::PermissionDenied=>return Err(e.into()),Err(_)=>{}}}let cg=Path::new("/sys/fs/cgroup/system.slice/sv-qwen80.service/cgroup.procs");if cg.exists()&&!fs::read_to_string(cg)?.trim().is_empty(){return Err("GRUPO_NO_VACIO".into())}Ok(())}
fn tree(src:&Path,dst:&Path)->R<()> {let m=fs::symlink_metadata(src)?;if m.file_type().is_symlink(){return Err("ENLACE".into())}if m.is_dir(){fs::create_dir(dst)?;for e in fs::read_dir(src)?{let e=e?;if ["target",".git"].iter().any(|s|e.file_name()==*s){continue}tree(&e.path(),&dst.join(e.file_name()))?}}else{if m.len()>20*1024*1024{return Err("FUENTE_FUERA_DE_COTA".into())}let b=fs::read(src)?;save(dst,&b)?;if fs::read(dst)?!=b{return Err("COPIA_DIVERGENTE".into())}}Ok(())}
fn custody()->R<()> {identity()?;let old=Path::new(OLD);let d=old.join("cierre-parametros");fs::create_dir(&d)?;stopped(&d)?;
 let conf=old.join("configuracion/preparacion.json");let original=fs::read(&conf)?;let mut v:Value=serde_json::from_slice(&original)?;if v["run_id"]!="examen09-20260930-03"{return Err("CONFIGURACION_DISTINTA".into())}save(&d.join("preparacion-ejecutada.json"),&original)?;v["allow_model_loading"]=json!(false);v["auto_start"]=json!(false);let b=serde_json::to_vec_pretty(&v)?;let tmp=old.join("configuracion/preparacion-cerrada-contexto.json");save(&tmp,&b)?;fs::rename(tmp,&conf)?;fs::File::open(conf.parent().unwrap())?.sync_all()?;
 command(&d,"servicios-conservados","systemctl",&["show","ssh.service","gdm.service","sv-qwen80.socket","-p","Id","-p","MainPID","-p","ActiveState","-p","UnitFileState"])?;
 command(&d,"diario-cierre","journalctl",&["-u","sv-qwen80.service","-u","sv-qwen80-examen-09-contexto.service","--since","2026-09-30 11:03:40 UTC","--no-pager","-o","short-iso-precise"])?;
 save(&d.join("CIERRE-CONFIGURACION.json"),&serde_json::to_vec_pretty(&json!({"utc_ms":now(),"procesos_propios_ausentes":true,"grupo_vacio_o_ausente":true,"configuracion_original_sha256":hash(&original),"configuracion_cerrada_sha256":hash(&b),"carga_deshabilitada":true,"estado_adverso_conservado":true,"instancia_eliminada":false}))?)?;
 let idx="recuperacion-contexto/INDICE-SEGMENTO-03.tsv";
 command(Path::new(BASE),"indice-segmento03","/opt/sv-qwen80/examen-09/bin/custodia-paquete",&["indice",idx,"recuperacion-contexto/recepcion","recuperacion-contexto/evidencias","recuperacion-contexto/supervisor","recuperacion-contexto/configuracion","recuperacion-contexto/cierre-parametros"])?;
 command(Path::new(BASE),"archivo-segmento03","tar",&["--exclude=EXPERTOS.jsonl","--exclude=*.sock","-czf","/opt/sv-qwen80/examen-09/recuperacion-contexto/EVIDENCIAS-SEGMENTO-03.tar.gz","-C",OLD,"recepcion","evidencias","supervisor","configuracion","cierre-parametros","INDICE-SEGMENTO-03.tsv"])?;
 command(Path::new(BASE),"traza-segmento03","tar",&["-czf","/opt/sv-qwen80/examen-09/recuperacion-contexto/TRAZA-SEGMENTO-03.tar.gz","-C",OLD,"recepcion/EXPERTOS.jsonl"])?;
 command(Path::new(BASE),"cotejo-segmento03","/opt/sv-qwen80/examen-09/bin/custodia-paquete",&["comprobar",idx])?;
 command(Path::new(BASE),"identidades-segmento03","/opt/sv-qwen80/examen-09/bin/custodia-paquete",&["hash","/opt/sv-qwen80/examen-09/recuperacion-contexto/EVIDENCIAS-SEGMENTO-03.tar.gz","/opt/sv-qwen80/examen-09/recuperacion-contexto/TRAZA-SEGMENTO-03.tar.gz","/opt/sv-qwen80/examen-09/recuperacion-contexto/INDICE-SEGMENTO-03.tsv"])?;
 println!("SEGMENTO_03_CUSTODIADO; FUENTES_04_PREPARADAS; MODELO_DETENIDO");Ok(())}
fn effective(d:&Path)->R<String>{let b=command(d,"configuracion-efectiva","systemctl",&["show","sv-qwen80.service","-p","ExecStart","-p","ExecStopPost","-p","BindPaths","-p","BindReadOnlyPaths","-p","MemoryMax","-p","MemorySwapMax","-p","CPUQuotaPerSecUSec","-p","PrivateNetwork","-p","PrivateDevices","-p","ProtectSystem","-p","ProtectHome","-p","NoNewPrivileges","-p","CapabilityBoundingSet","-p","RootDirectory","-p","Restart","-p","User","-p","Group"])?;let s=String::from_utf8(b)?;for t in ["MemoryMax=63350767616","MemorySwapMax=0","CPUQuotaPerSecUSec=11s","PrivateNetwork=yes","PrivateDevices=yes","ProtectSystem=strict","ProtectHome=yes","NoNewPrivileges=yes","CapabilityBoundingSet=\n","RootDirectory=/opt/sv-qwen80/recinto","Restart=no","User=svqwen","Group=svqwen",NEW]{if !s.contains(t){return Err(format!("PROTECCION_DISCORDANTE:{t}").into())}}Ok(s)}
fn prepare(expected:&str)->R<()> {identity()?;let root=Path::new(NEW);let d=root.join("evidencias/preparacion");fs::create_dir(&d)?;stopped(&d)?;let seconds=remaining()?;
 let mut checks=vec![];for n in ["pruebas-completas","compilacion"]{let p=root.join("evidencias").join(n);let v=read(p.join("RESULTADO.json"))?;if v["correcto"]!=true||v["codigo"]!=0||v["tiempo_agotado"]!=false{return Err(format!("COMPROBACION_ADVERSA:{n}").into())}checks.push(json!({"comprobacion":n,"resultado":v,"stdout_sha256":hash(&fs::read(p.join("stdout"))?)}));}
 for n in ["Cargo.toml","Cargo.lock"]{if fs::read(root.join("supervisor").join(n))?!=fs::read(Path::new(OLD).join("supervisor").join(n))?{return Err("DEPENDENCIAS_MODIFICADAS".into())}}
 let engine=fs::read(format!("{BASE}/bin/sv-qwen80-motor-local"))?;if hash(&engine)!="f31b133c32a7e6b3537f57f6c0d76a905916bd2fadabe1d3636f13a71e7f6770"{return Err("MOTOR_MODIFICADO".into())}
 let b=fs::read("/opt/sv-qwen80/target-integracion/release/sv-qwen80-integracion")?;if hash(&b)!=expected{return Err("COMPILADO_DISCORDANTE".into())}let exe=root.join("bin/sv-qwen80-integracion");save(&exe,&b)?;fs::set_permissions(&exe,fs::Permissions::from_mode(0o755))?;
 command(&d,"reconstruccion",exe.to_str().ok_or("UTF8")?,&["preparar-recuperacion-parametros"])?;
 let mut c=read(format!("{OLD}/cierre-parametros/preparacion-ejecutada.json"))?;c["base"]=json!(format!("{NEW}/recepcion"));c["run_id"]=json!(RUN);c["auto_start"]=json!(false);c["allow_model_loading"]=json!(true);save(&root.join("configuracion/preparacion.json"),&serde_json::to_vec_pretty(&c)?)?;
 command(&d,"propiedad-recepcion","chown",&["-R","svqwen:svqwen",&format!("{NEW}/recepcion")])?;command(&d,"modo-recepcion","chmod",&["0750",&format!("{NEW}/recepcion")])?;
 let paths=format!("/usr/lib /lib /lib64 /opt/sv-qwen80/bin {BASE}/bin {BASE}/configuracion /opt/sv-qwen80/modelos-q4k:/opt/sv-qwen80/modelos /opt/sv-qwen80/emulacion-dominio-inmunologia /sys/fs/cgroup {BASE}/banco {BASE}/recepcion {BASE}/indice-mcp {OLD}/recepcion {NEW}/bin {NEW}/configuracion");
 let text=format!("[Service]\nExecStart=\nExecStart={NEW}/bin/sv-qwen80-integracion supervisar {NEW}/configuracion/preparacion.json\nExecStopPost=\nExecStopPost={NEW}/bin/sv-qwen80-integracion cierre-exterior\nBindPaths=\nBindReadOnlyPaths=\nBindPaths={NEW}/recepcion\nBindReadOnlyPaths={paths}\nEnvironment=SV_QWEN_EXPERT_TRACE={NEW}/recepcion/EXPERTOS.jsonl\nRuntimeMaxSec={seconds}\n");
 save(Path::new("/etc/systemd/system/sv-qwen80.service.d/zz-recuperacion-parametros.conf"),text.as_bytes())?;save(&root.join("configuracion/zz-recuperacion-parametros.conf"),text.as_bytes())?;
 let driver=format!("[Unit]\nDescription=Continuación documental P16-P25 del examen Qwen80\nAfter=sv-qwen80.service\n[Service]\nType=simple\nRestart=no\nRuntimeMaxSec={seconds}\nTimeoutStopSec=1min\nKillMode=control-group\nExecStopPost=/usr/bin/systemctl stop sv-qwen80.service\nStandardOutput=append:{NEW}/evidencias/conductor.stdout\nStandardError=append:{NEW}/evidencias/conductor.stderr\nExecStart={NEW}/bin/sv-qwen80-integracion ejecutar-banco {NEW}/configuracion/preparacion.json\n");save(&Path::new("/etc/systemd/system").join(DRIVER),driver.as_bytes())?;save(&root.join("configuracion").join(DRIVER),driver.as_bytes())?;
 command(&d,"actualizar-definiciones","systemctl",&["daemon-reload"])?;let eff=effective(&d)?;for p in paths.split_whitespace(){if !eff.contains(p){return Err(format!("MONTAJE_AUSENTE:{p}").into())}}
 save(&root.join("PREPARACION-CONFORME.json"),&serde_json::to_vec_pretty(&json!({"utc_ms":now(),"conforme":true,"comprobaciones":checks,"supervisor_sha256":expected,"motor_sha256":hash(&engine),"configuracion":c,"configuracion_efectiva":eff,"plazo_original_utc_ms":1790787079791u64,"segundos_unidad":seconds,"carga_iniciada":false}))?)?;println!("PREPARACION_CONFORME; SIGUIENTE_P16; VENCIMIENTO_ORIGINAL");Ok(())}
fn activate()->R<()> {identity()?;remaining()?;let root=Path::new(NEW);let d=root.join("evidencias/activacion");fs::create_dir(&d)?;stopped(&d)?;let prep=read(root.join("PREPARACION-CONFORME.json"))?;if prep["conforme"]!=true||prep["supervisor_sha256"]!=hash(&fs::read(root.join("bin/sv-qwen80-integracion"))?){return Err("PREPARACION_DISCORDANTE".into())}effective(&d)?;
 save(&d.join("ACTIVACION-INICIADA.json"),&serde_json::to_vec(&json!({"utc_ms":now(),"segmento":RUN,"siguiente":"P16","plazo_original_utc_ms":1790787079791u64}))?)?;
 let outcome=(||->R<()>{command(&d,"inicio-supervisor","systemctl",&["start","sv-qwen80.service"])?;let socket=root.join(format!("recepcion/{RUN}.admin.sock"));let end=Instant::now()+Duration::from_secs(20);while !socket.exists(){if Instant::now()>end{return Err("CONTROL_AUSENTE".into())}std::thread::sleep(Duration::from_millis(100));}let mut s=UnixStream::connect(socket)?;s.set_read_timeout(Some(Duration::from_secs(15)))?;s.set_write_timeout(Some(Duration::from_secs(2)))?;s.write_all(b"{\"orden\":\"estado\"}\n")?;s.shutdown(std::net::Shutdown::Write)?;let mut b=vec![];s.take(65537).read_to_end(&mut b)?;save(&d.join("ESTADO-PREVIO.json"),&b)?;let v:Value=serde_json::from_slice(&b)?;if v.get("error").is_some()||v["modelo_cargado"]!=false||v["cargas_iniciadas"]!=0{return Err("ESTADO_PREVIO_DISCORDANTE".into())}command(&d,"inicio-conductor","systemctl",&["start",DRIVER])?;Ok(())})();if let Err(e)=outcome{let stop=command(&d,"parada-ante-fallo","systemctl",&["stop","sv-qwen80.service"]);save(&d.join("INCIDENCIA.json"),&serde_json::to_vec(&json!({"error":e.to_string(),"parada":stop.is_ok(),"utc_ms":now()}))?)?;return Err(e)}println!("ACTIVACION_SOLICITADA_P16");Ok(())}
fn main()->R<()>{let a:Vec<_>=std::env::args().collect();match a.get(1).map(String::as_str){Some("custodiar")=>custody(),Some("preparar")=>prepare(a.get(2).ok_or("SHA256_COMPILADO")?),Some("activar")=>activate(),_=>Err("MODO".into())}}
